CREATE
OR REPLACE TABLE FUNCTION `also-analytics-model-prod.2_NEGOCIO_S4.TF_ATVABRASCE_4B`() AS 

WITH var_vicncn AS (
SELECT
	CASE
		WHEN ZZCLASS_ZNATPB = '' THEN 'OUTROS'
		WHEN ZZCLASS_ZNATPB IS NULL THEN 'OUTROS'
		ELSE ZZCLASS_ZNATPB
	END AS ZZCLASS_ZNATPB,
	CASE
		WHEN ZZCLASS_ZGRABRASCE = '' THEN 'N/A'
		WHEN ZZCLASS_ZGRABRASCE IS NULL THEN 'N/A'
		ELSE ZZCLASS_ZGRABRASCE
	END AS ZZCLASS_ZGRABRASCE
FROM
	`also-analytics-model-prod.1_AQUISICAO_S4.vicncn`
GROUP BY
	ZZCLASS_ZNATPB,
	ZZCLASS_ZGRABRASCE
),

var_saida AS (
SELECT
	NATPB.CODNATPB,
	VICNCN.ZZCLASS_ZNATPB,
	MAX(GRPABRASCE.KEY_GRPABRASCE) AS KEY_GRPABRASCE,
	GRPABRASCE.SHP_CDSHOPPING
FROM
	var_vicncn AS VICNCN
	INNER JOIN `also-analytics-model-prod.3_MATERIALIZADO_S4.DIM_NATUREZA_PB` AS NATPB ON NATPB.ZENATPB = VICNCN.ZZCLASS_ZNATPB
	INNER JOIN `also-analytics-model-prod.2_NEGOCIO_S4.TF_GRPABRASCE_4B`() AS GRPABRASCE ON GRPABRASCE.ZGRABRASCE = VICNCN.ZZCLASS_ZGRABRASCE
GROUP BY
	NATPB.CODNATPB,
	VICNCN.ZZCLASS_ZNATPB,
	GRPABRASCE.SHP_CDSHOPPING
)

SELECT
	'S4' || '-' || SAIDA.SHP_CDSHOPPING || '-' || SAIDA.CODNATPB AS ATA_CDATIVIDADE,
	SAIDA.ZZCLASS_ZNATPB AS ATA_DSATIVIDADE,
	LEFT(SAIDA.KEY_GRPABRASCE, 10) AS ATA_CDGRUPO,
	SAIDA.SHP_CDSHOPPING AS ATA_CDSHOPPING,
	SAIDA.SHP_CDSHOPPING AS CC_CDSHOPPING
FROM
	var_saida AS SAIDA