CREATE OR REPLACE TABLE FUNCTION `also-analytics-model-nonprod.2_NEGOCIO_S4.TF_CONTRATO_CONDICAO_4B`() 
AS
    WITH var_calcrule_text AS (
        SELECT
            'A' AS CALCRULE,
            'Montante fixo' AS CALCRULE_TEXT
        UNION
        ALL
        SELECT
            'E1' AS CALCRULE,
            '% em uma condição' AS CALCRULE_TEXT
        UNION
        ALL
        SELECT
            'U' AS CALCRULE,
            'Aluguel baseado no faturamento' AS CALCRULE_TEXT
        UNION
        ALL
        SELECT
            'V' AS CALCRULE,
            'Medição diferente' AS CALCRULE_TEXT
    ),

    var_condicao AS (
        SELECT
            VICDCOND.INTRENO AS INTRENO_VICNCN,
            VICDCOND.CONDTYPE,
            VICDCOND.CONDVALIDFROM,
            VICDCOND.CONDVALIDTO,
            VICDCOND.CALCRULE,
            VICDCOND.CALCRULEPARA1,
            VICDCOND.CALCRULEPARA2,
            NULL AS CONDTYPE_CALC,
            VICDCOND.UNITPRICE,
            VICDCONDCALC.VALUEVALIDFROM,
            VICDCONDCALC.VALUEVALIDTO,
            VICDCONDCALC.CALCVALUE,
            VICDCONDCALC.CONDVALUE,
            IFNULL(
                VICDCONDCALC.VALUEVALIDFROM,
                VICDCOND.CONDVALIDFROM
            ) AS CC_VALIDFROM,
            IFNULL(VICDCONDCALC.VALUEVALIDTO, VICDCOND.CONDVALIDTO) AS CC_VALIDTO
        FROM
            `also-analytics-model-nonprod.1_AQUISICAO_S4.vicdcond` AS VICDCOND
            LEFT OUTER JOIN `also-analytics-model-nonprod.1_AQUISICAO_S4.vicdcondcalc` AS VICDCONDCALC ON VICDCONDCALC.INTRENO = VICDCOND.INTRENO
            AND VICDCONDCALC.CONDTYPE = VICDCOND.CONDTYPE
            AND VICDCONDCALC.CONDVALIDFROM = VICDCOND.CONDVALIDFROM
        WHERE
            VICDCOND.CONDDELETE = ''
            AND VICDCOND.CALCRULE IN ('A', 'V')
        UNION
        DISTINCT
        SELECT
            VICDCOND.INTRENO AS INTRENO_VICNCN,
            VICDCOND.CONDTYPE,
            VICDCOND.CONDVALIDFROM,
            VICDCOND.CONDVALIDTO,
            VICDCOND.CALCRULE,
            VICDCOND.CALCRULEPARA1,
            VICDCOND.CALCRULEPARA2,
            'CALCRULEPARA1' AS CONDTYPE_CALC,
            --SUBSTR_REGEXPR('[Z]\d{3}' IN CALCRULEPARA1 )						AS CONDTYPE_CALC,
            VICDCOND.UNITPRICE,
            VICDCOND.CONDVALIDFROM AS VALUEVALIDFROM,
            VICDCOND.CONDVALIDTO AS VALUEVALIDTO,
            0 AS CALCVALUE,
            0 AS CONDVALUE,
            VICDCOND.CONDVALIDFROM AS CC_VALIDFROM,
            VICDCOND.CONDVALIDTO AS CC_VALIDTO
        FROM
            `also-analytics-model-nonprod.1_AQUISICAO_S4.vicdcond` AS VICDCOND
        WHERE
            VICDCOND.CONDDELETE = ''
            AND VICDCOND.CALCRULE IN ('E1')
        UNION
        DISTINCT
        SELECT
            VICDCOND.INTRENO AS INTRENO_VICNCN,
            VICDCOND.CONDTYPE,
            VICDCOND.CONDVALIDFROM,
            VICDCOND.CONDVALIDTO,
            VICDCOND.CALCRULE,
            VICDCOND.CALCRULEPARA1,
            VICDCOND.CALCRULEPARA2,
            NULL AS CONDTYPE_CALC,
            VICDCOND.UNITPRICE,
            VICDCOND.CONDVALIDFROM AS VALUEVALIDFROM,
            VICDCOND.CONDVALIDTO AS VALUEVALIDTO,
            0 AS CALCVALUE,
            0 AS CONDVALUE,
            VICDCOND.CONDVALIDFROM AS CC_VALIDFROM,
            VICDCOND.CONDVALIDTO AS CC_VALIDTO
        FROM
            `also-analytics-model-nonprod.1_AQUISICAO_S4.vicdcond` AS VICDCOND
        WHERE
            VICDCOND.CONDDELETE = ''
            AND VICDCOND.CALCRULE IN ('U')
    ),
    
    DIM_CONDICAO AS (
        SELECT
            *
        FROM
            `also-analytics-model-nonprod.3_MATERIALIZADO_S4.DIM_CONDICAO`
    )
    SELECT
        CONTR.CSHP_CDSHOPPING as CSHP_CDSHOPPING,
        COND.INTRENO_VICNCN as INTRENO_VICNCN,
        CONTR.BUKRS as BUKRS,
        CONTR.RECNNR as RECNNR,
        CONTR.SMIVE as SMIVE,
        CONTR.XMETXT as XMETXT,
        CONTR.SMENR as SMENR,
        CONTR.INTRENO as INTRENO,
        CONTR.DMIBEG as DMIBEG,
        CONTR.DMIEND as DMIEND,
        COND.CONDTYPE as CONDTYPE,
        DIM_COND.CONDTYPE_TEXT30 as CONDTYPE_TEXT30,
        COND.CONDVALIDFROM as CONDVALIDFROM,
        COND.CONDVALIDTO as CONDVALIDTO,
        COND.CALCRULE as CALCRULE,
        TEXT.CALCRULE_TEXT as CALCRULE_TEXT,
        COND.CALCRULEPARA1 as CALCRULEPARA1,
        COND.CALCRULEPARA2 as CALCRULEPARA2,
        COND.CONDTYPE_CALC as CONDTYPE_CALC,
        COND.UNITPRICE as UNITPRICE,
        COND.VALUEVALIDFROM as VALUEVALIDFROM,
        COND.VALUEVALIDTO as VALUEVALIDTO,
        COND.CALCVALUE as CALCVALUE,
        COND.CONDVALUE as CONDVALUE,
        COND.CC_VALIDFROM as CC_VALIDFROM,
        COND.CC_VALIDTO as CC_VALIDTO,
        CASE
            WHEN IFNULL(COND.CONDVALUE, 0) = 0 THEN COND.UNITPRICE
            ELSE COND.CONDVALUE
        END AS CC_CONDVALUE
    FROM
        var_condicao AS COND
        LEFT OUTER JOIN var_calcrule_text AS TEXT ON TEXT.CALCRULE = COND.CALCRULE
        LEFT OUTER JOIN DIM_CONDICAO AS DIM_COND ON DIM_COND.CONDTYPE = COND.CONDTYPE
        LEFT OUTER JOIN `also-analytics-model-nonprod.3_MATERIALIZADO_S4.DIM_CONTRATO` AS CONTR
			        ON CONTR.INTRENO_VICNCN = COND.INTRENO_VICNCN