CREATE OR REPLACE TABLE FUNCTION `also-analytics-model-nonprod.2_NEGOCIO_S4.TF_CONTRATO_CLAUSULA_4B` ()

AS
SELECT
  CONTR.INTRENO_VICNCN,
  CONTR.CSHP_CDSHOPPING,
  CONTR.BUKRS,
  CONTR.RECNNR,
  CONTR.CC_CDCONTRATO,
  VITMTERM.TERMTYPE,
  TIVTMTERMTYPET.XTERMTYPE,
  VIAJSPECINDX.TERMNO,
  VIAJSPECINDX.ADJMRULE,
  TIVAJRULET_1.XADJMRULE AS ADJMRULE_TEXT60,
  VIAJSPECINDX.ADJMSUBRULE,
  TIVAJRULET_2.XADJMRULE AS ADJMSUBRULE_TEXT60,
  VIAJSPECINDX.VALIDFROM,
  VIAJSPECINDX.VALIDTO,
  VIAJSPECINDX.INDEXSERIES,
  T094T.INDTXT,
  VIAJSPECINDX.INDEXBASEYEAR,
  VIAJOBJINDX.FIRSTINDEXDATE,
  VIAJOBJINDX.ADJMFIRSTDATE,
  TIVAJRULE.RHYTHM,
  TIVAJRULE.RHYTHMUNIT,
  CASE WHEN TIVAJRULE.RHYTHMUNIT = '0' THEN 'Meses'
      WHEN TIVAJRULE.RHYTHMUNIT = '1' THEN 'Trimestres'
      WHEN TIVAJRULE.RHYTHMUNIT = '2' THEN 'Anos'
  END AS RHYTHMUNIT_TEXT,
  CASE WHEN TIVAJRULE.RHYTHMUNIT = '0' THEN 'MEN'
      WHEN TIVAJRULE.RHYTHMUNIT = '2' AND TIVAJRULE.RHYTHM = '001' THEN 'ANU'
      WHEN TIVAJRULE.RHYTHMUNIT = '2' AND TIVAJRULE.RHYTHM = '002' THEN 'BIM'
      ELSE 'SEM'
  END AS CC_PERIO_REAJUSTE
FROM `also-analytics-model-nonprod.1_AQUISICAO_S4.vitmterm` AS VITMTERM
LEFT OUTER JOIN `also-analytics-model-nonprod.3_MATERIALIZADO_S4.DIM_CONTRATO` AS CONTR
  ON CONTR.INTRENO_VICNCN = VITMTERM.INTRENO
LEFT OUTER JOIN `also-analytics-model-nonprod.1_AQUISICAO_S4.tivtmtermtypet` AS TIVTMTERMTYPET
  ON  TIVTMTERMTYPET.TERMTYPE = VITMTERM.TERMTYPE
  AND TIVTMTERMTYPET.OBJTYPE  = 'IS'
  AND TIVTMTERMTYPET.SPRAS    = 'P'
LEFT OUTER JOIN `also-analytics-model-nonprod.1_AQUISICAO_S4.viajspecindx` AS VIAJSPECINDX
  ON  VITMTERM.INTRENO  = VIAJSPECINDX.INTRENO
  AND VITMTERM.TERMTYPE = '1300'
LEFT OUTER JOIN `also-analytics-model-nonprod.1_AQUISICAO_S4.tivajrule` AS TIVAJRULE
  ON  TIVAJRULE.ADJMRULE = VIAJSPECINDX.ADJMRULE
LEFT OUTER JOIN `also-analytics-model-nonprod.1_AQUISICAO_S4.tivajrulet` AS TIVAJRULET_1
  ON  TIVAJRULET_1.ADJMRULE = VIAJSPECINDX.ADJMRULE
  AND TIVAJRULET_1.SPRAS    = 'P'
LEFT OUTER JOIN `also-analytics-model-nonprod.1_AQUISICAO_S4.tivajrulet` AS TIVAJRULET_2
  ON  TIVAJRULET_2.ADJMRULE = VIAJSPECINDX.ADJMSUBRULE
  AND TIVAJRULET_2.SPRAS    = 'P'
LEFT OUTER JOIN `also-analytics-model-nonprod.1_AQUISICAO_S4.t094t` AS T094T
  ON  T094T.WBIND = VIAJSPECINDX.INDEXSERIES
  AND T094T.SPRAS = 'P'
LEFT OUTER JOIN `also-analytics-model-nonprod.1_AQUISICAO_S4.viajobjindx` AS VIAJOBJINDX
  ON  VIAJOBJINDX.INTRENO     = VIAJSPECINDX.INTRENO
  AND VIAJOBJINDX.TERMNO      = VIAJSPECINDX.TERMNO
  AND VIAJOBJINDX.ADJMRULE    = VIAJSPECINDX.ADJMRULE
  AND VIAJOBJINDX.ADJMSUBRULE = VIAJSPECINDX.ADJMSUBRULE
  AND VIAJOBJINDX.VALIDFROM   = VIAJSPECINDX.VALIDFROM