CREATE OR REPLACE TABLE FUNCTION
`also-analytics-model-nonprod.2_NEGOCIO_S4.TF_DESCONTO_4B` (IP_COMPETENCIA STRING) AS (
	
WITH 			
	
var_hkont AS (
    SELECT '3910101001' AS HKONT, 'Carência - Aluguel' AS HKONT_TEXT, 0 AS CC_CDTPCONTA UNION DISTINCT
    SELECT '3910101007' AS HKONT, 'Desconto Pré - CTO' AS HKONT_TEXT, 0 AS CC_CDTPCONTA UNION DISTINCT
    SELECT '3910101006' AS HKONT, 'Desconto Pré - Aluguel' AS HKONT_TEXT, 0 AS CC_CDTPCONTA UNION DISTINCT
    SELECT '3910101012' AS HKONT, 'Desconto Pré - Lojas Temp. Cond.' AS HKONT_TEXT, 0 AS CC_CDTPCONTA UNION DISTINCT
    SELECT '3910101013' AS HKONT, 'Desconto Pré - Lojas Temp.' AS HKONT_TEXT, 0 AS CC_CDTPCONTA UNION DISTINCT
    SELECT '3910101009' AS HKONT, 'Desconto Pré - Quiosque' AS HKONT_TEXT, 0 AS CC_CDTPCONTA UNION DISTINCT
    SELECT '3910101008' AS HKONT, 'Desconto Pré - Quiosque Cond.' AS HKONT_TEXT, 0 AS CC_CDTPCONTA UNION DISTINCT
    SELECT '3910101010' AS HKONT, 'Desconto Pré - Mídia Cond.'	AS HKONT_TEXT, 0 AS CC_CDTPCONTA UNION DISTINCT
    SELECT '3910101011' AS HKONT, 'Desconto Pré - Mídia' AS HKONT_TEXT, 0 AS CC_CDTPCONTA UNION DISTINCT
    SELECT '3910101014' AS HKONT, 'Desconto Pré - Corporativo' AS HKONT_TEXT, 0 AS CC_CDTPCONTA UNION DISTINCT
    SELECT '3910101005' AS HKONT, 'Desconto Pré - Aluguel Cond.' AS HKONT_TEXT, 0 AS CC_CDTPCONTA UNION DISTINCT
    SELECT '3910101016' AS HKONT, 'Cancelamento' AS HKONT_TEXT, 0 AS CC_CDTPCONTA UNION DISTINCT
    SELECT '3910101017' AS HKONT, 'Desconto Encargo' AS HKONT_TEXT, 1 AS CC_CDTPCONTA UNION DISTINCT
    SELECT '3910101018' AS HKONT, 'Desconto FPP' AS HKONT_TEXT, 2 AS CC_CDTPCONTA UNION DISTINCT
    SELECT '3910101015' AS HKONT, 'Desconto Pós' AS HKONT_TEXT, 0 AS CC_CDTPCONTA UNION DISTINCT
    SELECT '4110107001' AS HKONT, 'Perdas Contas a Rec. - Aluguéis  Quiosques E Midia' AS HKONT_TEXT, 0 AS CC_CDTPCONTA UNION DISTINCT
    SELECT '4110107002' AS HKONT, 'Perdas Contas a Rec. - CDU' AS HKONT_TEXT, 3 AS CC_CDTPCONTA UNION DISTINCT
    SELECT '4110107003' AS HKONT, 'Perdas Contas a Rec. - Condomínio' AS HKONT_TEXT, 1 AS CC_CDTPCONTA
),
 

var_vicnnt AS (
    SELECT 
        T1.*
    FROM `also-analytics-model-nonprod.1_AQUISICAO_S4.vicnnt` AS T1
    INNER JOIN (
        SELECT
            INTRENO,
            MAX(NTNO) AS NTNO
        FROM `also-analytics-model-nonprod.1_AQUISICAO_S4.vicnnt`
        GROUP BY INTRENO) AS T2
    ON  T1.INTRENO = T2.INTRENO
    AND T1.NTNO    = T2.NTNO
),
		
		
var_contr AS (
    SELECT
        CONTR.CSHP_CDSHOPPING,
        CONTR.INTRENO_VICNCN,
        CONTR.CC_CDCONTRATO,
        CONTR.BUKRS,
        UE.XWETEXT,
        CONTR.SWENR,
        OL.SMENR,
        OL.XMETXT,
        OL.SSTOCKW,
        OL.SSTCKBIS,
        OL.RLGESCH,
        VICNNT.NTPER,
        CONTR.RECNNR,
        CONTR.RECNTYPE,
        CONTR.RECNTYPE_TEXT30,
        CONTR.RECNTXT,
        T001Z.PAVAL,
        CONTR.RECNBEG,
        CONTR.ZZREDILJ,
        CONTR.RECNENDABS,
        CONTR.CODNATPB,
        CONTR.ZZCLASS_ZNATPB,
        CONTR.ZCODREDE,
        CONTR.ZZCLASS_ZREDE,
        CONTR.ZCODABL,
        CONTR.ZZCLASS_ZGRABL,
        CONTR.ZCODABRASCE,
        CONTR.ZZCLASS_ZGRABRASCE,
        CONTR.OBJNR,
        CONTR.PARTNER_TR0200,
        CONTR.PARTNER_TR0600,
        CONTR.PARTNER_TR0605,
        CONTR.PARTNER_TR0806,
        CONTR.CC_DIAS_VENCTO,
        CONTR.CC_FQMFLART_SONAE, 
        CONTR.FQMFLART
    FROM `also-analytics-model-nonprod.3_MATERIALIZADO_S4.DIM_CONTRATO` AS CONTR
    LEFT OUTER JOIN `also-analytics-model-nonprod.3_MATERIALIZADO_S4.DIM_UNIDADE_ECONOMICA` AS UE
        ON UE.INTRENO_VIBDBE = CONTR.INTRENO_VIBDBE
    LEFT OUTER JOIN `also-analytics-model-nonprod.3_MATERIALIZADO_S4.DIM_OBJETO_LOCACAO` AS OL
        ON OL.INTRENO_VIBDRO = CONTR.INTRENO_VIBDRO
    LEFT OUTER JOIN var_vicnnt AS VICNNT
        ON VICNNT.INTRENO = CONTR.INTRENO_VICNCN
    LEFT OUTER JOIN `also-analytics-model-nonprod.1_AQUISICAO_S4.t001z` AS T001Z
        ON  T001Z.BUKRS = CONTR.BUKRS
        AND T001Z.PARTY = 'J_1BCG'
),
				
var_doc_desconto AS (
    SELECT 
        BSEG.BUKRS, 
        BSEG.BELNR,
        CASE WHEN BSEG.SHKZG = 'H' THEN (BSEG.WRBTR * -1) ELSE BSEG.WRBTR END AS WRBTR,
        BSEG.ZBD1P, 
        BSEG.BSCHL,
        BSEG.NETDT,
        BSEG.KUNNR,
        BSEG.HKONT,
        BSEG.UMSKZ,
        BSEG.AUGDT,
        BSEG.AUGBL,
        BSEG.AUGGJ,
        BSEG.ZUONR,
        BSEG.GJAHR,
        BSEG.BUZEI,
        BSEG.SHKZG,
        BSEG.VERTN,
        BSEG.REBZG,
        BSEG.REBZJ,
        BSEG.REBZZ,
        BKPF.BUDAT,
        BKPF.BLART,
        BKPF.BLDAT,
        BSEG.GSBER,
        BSEG.ZFBDT,
        BKPF.STBLG,
        BKPF.GJAHR || BKPF.MONAT AS CALMONTH
    FROM `also-analytics-model-nonprod.1_AQUISICAO_S4.bseg` AS BSEG
    INNER JOIN `also-analytics-model-nonprod.1_AQUISICAO_S4.bkpf` AS BKPF
        ON  BKPF.BUKRS = BSEG.BUKRS
        AND BKPF.BELNR = BSEG.BELNR
        AND BKPF.GJAHR = BSEG.GJAHR
    WHERE BKPF.GJAHR || BKPF.MONAT = IP_COMPETENCIA
        AND BSEG.HKONT IN (SELECT HKONT FROM var_hkont)
        AND BKPF.STBLG = ''
), 
		  
var_doc_original AS (
    SELECT
        BSEG.BUKRS, 
        BSEG.AUGGJ,
        BSEG.AUGBL,
        MAX(BSEG.GSBER) AS GSBER,
        MAX(BSEG.ZUONR) AS ZUONR,
        MAX(BSEG.VERTN) AS VERTN,
        MAX(BSEG.ZBD1P) AS ZBD1P,
        MAX(BKPF.GJAHR) || MAX(BKPF.MONAT) AS CALMONTH
    FROM `also-analytics-model-nonprod.1_AQUISICAO_S4.bseg` AS BSEG
    INNER JOIN `also-analytics-model-nonprod.1_AQUISICAO_S4.bkpf` AS BKPF
        ON  BKPF.BUKRS = BSEG.BUKRS
        AND BKPF.BELNR = BSEG.BELNR
        AND BKPF.GJAHR = BSEG.GJAHR
    INNER JOIN var_contr AS CONTR
        ON  BSEG.BUKRS = CONTR.BUKRS
        AND (BSEG.VERTN = CONTR.RECNNR OR BSEG.ZUONR = CONTR.RECNNR)
    INNER JOIN var_doc_desconto AS DESCONT
        ON  BSEG.AUGGJ = DESCONT.GJAHR
        AND BSEG.AUGBL = DESCONT.BELNR
        AND BSEG.BUKRS = DESCONT.BUKRS
    GROUP BY
        BSEG.BUKRS,
        BSEG.AUGGJ,
        BSEG.AUGBL
),
						
var_doc_out AS (
    SELECT 
        DESCONT.BUKRS, 
        DESCONT.BELNR,
        DESCONT.WRBTR, 
        DESCONT.ZBD1P, 
        DESCONT.BSCHL,
        DESCONT.NETDT,
        DESCONT.KUNNR,
        DESCONT.HKONT,
        DESCONT.UMSKZ,
        DESCONT.AUGDT,
        DESCONT.AUGBL,
        DESCONT.AUGGJ,
        CASE WHEN DESCONT.ZUONR = '' THEN IFNULL(ORIG.ZUONR, '') ELSE DESCONT.ZUONR END AS ZUONR,
        DESCONT.GJAHR,
        DESCONT.BUZEI,
        DESCONT.SHKZG,
        CASE WHEN DESCONT.VERTN = '' THEN IFNULL(ORIG.VERTN, '') ELSE DESCONT.VERTN END AS VERTN,
        DESCONT.REBZG,
        DESCONT.REBZJ,
        DESCONT.REBZZ,
        DESCONT.BUDAT,
        DESCONT.BLART,
        DESCONT.BLDAT,
        DESCONT.GSBER,
        DESCONT.ZFBDT,
        DESCONT.STBLG,
        DESCONT.CALMONTH,
        CASE WHEN IFNULL(ORIG.ZBD1P, 0) = 0 THEN 0 ELSE 1 END AS FLAG_DESC_CONDICIONAL,
        CASE WHEN IFNULL(ORIG.ZBD1P, 0) = 0 THEN 1 ELSE 0 END AS FLAG_DESC_CLASSICO
    FROM var_doc_desconto AS DESCONT
    LEFT OUTER JOIN var_doc_original AS ORIG
        ON  DESCONT.GJAHR = ORIG.AUGGJ
        AND DESCONT.BELNR = ORIG.AUGBL
        AND DESCONT.BUKRS = ORIG.BUKRS
),
					
var_doc_total AS (
    SELECT 
        BSEG.BUKRS, 
        BSEG.BELNR,
        BSEG.WRBTR, 
        BSEG.ZBD1P, 
        BSEG.BSCHL,
        BSEG.NETDT,
        BSEG.KUNNR,
        BSEG.HKONT,
        BSEG.UMSKZ,
        BSEG.AUGDT,
        BSEG.AUGBL,
        BSEG.AUGGJ,
        BSEG.ZUONR,
        BSEG.GJAHR,
        BSEG.BUZEI,
        BSEG.SHKZG,
        BSEG.VERTN,
        BSEG.REBZG,
        BSEG.REBZJ,
        BSEG.REBZZ,
        BSEG.BUDAT,
        BSEG.BLART,
        BSEG.BLDAT,
        BSEG.GSBER,
        BSEG.ZFBDT,
        CONTR.RECNNR,
        BSEG.CALMONTH,
        CASE WHEN BSEG.HKONT = '3910101001' THEN WRBTR	ELSE 0 END AS VLCAR_TOT,
        CASE WHEN BSEG.HKONT = '3910101007' THEN WRBTR	ELSE 0 END AS VLDESC_PRE_CTO,
        CASE WHEN BSEG.HKONT = '3910101006' THEN WRBTR	ELSE 0 END AS VLDESC_PRE_ALUG,
        CASE WHEN BSEG.HKONT = '3910101005' THEN WRBTR	ELSE 0 END AS VLDESC_PRE_COND_PAG,
        CASE WHEN BSEG.HKONT = '3910101014' THEN WRBTR	ELSE 0 END AS VLDESC_PRE_EXTRA,
        CASE WHEN BSEG.HKONT = '3910101016' THEN WRBTR	ELSE 0 END AS VLCANCELAMENTO_TOT,
        CASE WHEN BSEG.HKONT = '3910101017' THEN WRBTR	ELSE 0 END AS VLDESC_ENCARGO,
        CASE WHEN BSEG.HKONT = '3910101018' THEN WRBTR	ELSE 0 END AS VLDESC_FPP,
        CASE WHEN BSEG.HKONT = '3910101015' THEN WRBTR * FLAG_DESC_CLASSICO	ELSE 0 END AS VLDESC_POS,
        CASE WHEN BSEG.HKONT IN ('3910101012', '3910101013') THEN WRBTR ELSE 0 END AS VLDESC_PRE_LOJA_TEMP,
        CASE WHEN BSEG.HKONT IN ('3910101008', '3910101009') THEN WRBTR	ELSE 0 END AS VLDESC_PRE_MALL,
        CASE WHEN BSEG.HKONT IN ('3910101010', '3910101011') THEN WRBTR ELSE 0 END AS VLDESC_PRE_MIDIA,
        CASE WHEN BSEG.HKONT IN ('4110107001', '4110107002', '4110107003') THEN WRBTR ELSE 0 END AS VLDESC_PERDAO_DIVIDA,
        CASE WHEN BSEG.HKONT IN ('3910101015') THEN WRBTR * FLAG_DESC_CONDICIONAL ELSE 0 END AS VLDESC_CONDICIONAL_POS_TOT,
        CASE WHEN BSEG.HKONT IN ('3910101005', '3910101012', '3910101010', '3910101008') THEN WRBTR  							ELSE 0 END AS VLDESC_CONDICIONAL_PRE_TOT,
        0 AS CC_DESCONTO_PRO,
        0 AS CC_DESCONTO_PAR
    FROM var_doc_out AS BSEG
    INNER JOIN var_contr AS CONTR
        ON  CONTR.BUKRS  = BSEG.BUKRS
        AND (CONTR.RECNNR = BSEG.VERTN OR CONTR.RECNNR = BSEG.ZUONR)
    
UNION DISTINCT
    
    SELECT 
        PRO.BUKRS, 
        PRO.BELNR,
        PRO.WRBTR, 
        BSEG.ZBD1P, 
        BSEG.BSCHL,
        BSEG.NETDT,
        BSEG.KUNNR,
        BSEG.HKONT,
        BSEG.UMSKZ,
        BSEG.AUGDT,
        BSEG.AUGBL,
        BSEG.AUGGJ,
        PRO.ZUONR,
        PRO.GJAHR,
        PRO.BUZEI,
        PRO.SHKZG,
        PRO.VERTN,
        BSEG.REBZG,
        BSEG.REBZJ,
        BSEG.REBZZ,
        BKPF.BUDAT,
        BKPF.BLART,
        BKPF.BLDAT,
        BSEG.GSBER,
        BSEG.ZFBDT,
        PRO.RECNNR,
        PRO.CALMONTH,
        0 AS VLCAR_TOT,
        0 AS VLDESC_PRE_CTO,
        0 AS VLDESC_PRE_ALUG,
        0 AS VLDESC_PRE_COND_PAG,
        0 AS VLDESC_PRE_EXTRA,
        0 AS VLCANCELAMENTO_TOT,
        0 AS VLDESC_ENCARGO,
        0 AS VLDESC_FPP,
        0 AS VLDESC_POS,
        0 AS VLDESC_PRE_LOJA_TEMP,
        0 AS VLDESC_PRE_MALL,
        0 AS VLDESC_PRE_MIDIA,
        0 AS VLDESC_PERDAO_DIVIDA,
        0 AS VLDESC_CONDICIONAL_POS_TOT,
        0 AS VLDESC_CONDICIONAL_PRE_TOT,
        PRO.CC_DESCONTO_PRO AS CC_DESCONTO_PRO,
        0 AS CC_DESCONTO_PAR
    FROM `also-analytics-model-nonprod.3_MATERIALIZADO_S4.PRORROGACAO` AS PRO
    LEFT OUTER JOIN `also-analytics-model-nonprod.1_AQUISICAO_S4.bseg` AS BSEG
        ON  BSEG.BUKRS = PRO.BUKRS
        AND BSEG.BELNR = PRO.BELNR
        AND BSEG.GJAHR = PRO.GJAHR
        AND BSEG.BUZEI = PRO.BUZEI
    INNER JOIN `also-analytics-model-nonprod.1_AQUISICAO_S4.bkpf` AS BKPF
        ON  BKPF.BUKRS = BSEG.BUKRS
        AND BKPF.BELNR = BSEG.BELNR
        AND BKPF.GJAHR = BSEG.GJAHR
    WHERE PRO.CALMONTH = IP_COMPETENCIA
        AND PRO.CC_DESCONTO_PRO <> 0
        
UNION DISTINCT
    
    SELECT 
        PAR.BUKRS, 
        PAR.BELNR,
        PAR.WRBTR, 
        BSEG.ZBD1P, 
        BSEG.BSCHL,
        BSEG.NETDT,
        BSEG.KUNNR,
        BSEG.HKONT,
        BSEG.UMSKZ,
        BSEG.AUGDT,
        BSEG.AUGBL,
        BSEG.AUGGJ,
        PAR.ZUONR,
        PAR.GJAHR,
        PAR.BUZEI,
        PAR.SHKZG,
        PAR.VERTN,
        BSEG.REBZG,
        BSEG.REBZJ,
        BSEG.REBZZ,
        BKPF.BUDAT,
        BKPF.BLART,
        BKPF.BLDAT,
        BSEG.GSBER,
        BSEG.ZFBDT,
        PAR.RECNNR,
        PAR.CALMONTH,
        0 AS VLCAR_TOT,
        0 AS VLDESC_PRE_CTO,
        0 AS VLDESC_PRE_ALUG,
        0 AS VLDESC_PRE_COND_PAG,
        0 AS VLDESC_PRE_EXTRA,
        0 AS VLCANCELAMENTO_TOT,
        0 AS VLDESC_ENCARGO,
        0 AS VLDESC_FPP,
        0 AS VLDESC_POS,
        0 AS VLDESC_PRE_LOJA_TEMP,
        0 AS VLDESC_PRE_MALL,
        0 AS VLDESC_PRE_MIDIA,
        0 AS VLDESC_PERDAO_DIVIDA,
        0 AS VLDESC_CONDICIONAL_POS_TOT,
        0 AS VLDESC_CONDICIONAL_PRE_TOT,
        0 AS CC_DESCONTO_PRO,
        CC_DESCONTO_PAR AS CC_DESCONTO_PAR
    FROM `also-analytics-model-nonprod.3_MATERIALIZADO_S4.PARCELAMENTO` AS PAR
    LEFT OUTER JOIN `also-analytics-model-nonprod.1_AQUISICAO_S4.bseg` AS BSEG
        ON  BSEG.BUKRS = PAR.BUKRS
        AND BSEG.BELNR = PAR.BELNR
        AND BSEG.GJAHR = PAR.GJAHR
        AND BSEG.BUZEI = PAR.BUZEI
    INNER JOIN `also-analytics-model-nonprod.1_AQUISICAO_S4.bkpf` AS BKPF
        ON  BKPF.BUKRS = BSEG.BUKRS
        AND BKPF.BELNR = BSEG.BELNR
        AND BKPF.GJAHR = BSEG.GJAHR
    WHERE PAR.CALMONTH = IP_COMPETENCIA
        AND PAR.CC_DESCONTO_PAR <> 0
),		  	  
		  
var_doc_sum AS (
    SELECT
        'S' AS FLAG_LANC_BSEG,
        CALMONTH,
        BUKRS,
        RECNNR,
        KUNNR,
        HKONT,
        UMSKZ,
        AUGDT,
        AUGBL,
        AUGGJ,
        ZUONR,
        GJAHR,
        BUZEI,
        SHKZG,
        VERTN,
        REBZG,
        REBZJ,
        REBZZ,
        BUDAT,
        BLART,
        BLDAT,
        GSBER,
        ZFBDT,
        BELNR,
        SUM(WRBTR) AS WRBTR,
        IFNULL(SUM(VLCAR_TOT), 0) AS VLCAR_TOT,
        IFNULL(SUM(VLDESC_PRE_CTO), 0 )AS VLDESC_PRE_CTO,
        IFNULL(SUM(VLDESC_PRE_ALUG), 0) AS VLDESC_PRE_ALUG,
        IFNULL(SUM(VLDESC_PRE_LOJA_TEMP), 0) AS VLDESC_PRE_LOJA_TEMP,
        IFNULL(SUM(VLDESC_PRE_MALL), 0) AS VLDESC_PRE_MALL,
        IFNULL(SUM(VLDESC_PRE_MIDIA), 0) AS VLDESC_PRE_MIDIA,
        IFNULL(SUM(VLDESC_PRE_COND_PAG), 0) AS VLDESC_PRE_COND_PAG,
        IFNULL(SUM(VLDESC_PRE_EXTRA), 0) AS VLDESC_PRE_EXTRA,
        IFNULL(SUM(VLCANCELAMENTO_TOT), 0) AS VLCANCELAMENTO_TOT,
        IFNULL(SUM(CC_DESCONTO_PRO), 0) AS CC_DESCONTO_PRO,
        IFNULL(SUM(CC_DESCONTO_PAR), 0)	AS CC_DESCONTO_PAR,
        IFNULL(SUM(VLDESC_ENCARGO), 0) AS VLDESC_ENCARGO,
        IFNULL(SUM(VLDESC_FPP), 0) AS VLDESC_FPP,
        IFNULL(SUM(VLDESC_POS), 0) AS VLDESC_POS,
        IFNULL(SUM(VLDESC_PERDAO_DIVIDA), 0) AS VLDESC_PERDAO_DIVIDA,
        IFNULL(SUM(VLDESC_CONDICIONAL_POS_TOT), 0) AS VLDESC_CONDICIONAL_POS_TOT,
        IFNULL(SUM(VLDESC_CONDICIONAL_PRE_TOT), 0) AS VLDESC_CONDICIONAL_PRE_TOT
    FROM var_doc_total
    GROUP BY
        CALMONTH,
        BUKRS,
        RECNNR,
        KUNNR,
        HKONT,
        UMSKZ,
        AUGDT,
        AUGBL,
        AUGGJ,
        ZUONR,
        GJAHR,
        BUZEI,
        SHKZG,
        VERTN,
        REBZG,
        REBZJ,
        REBZZ,
        BUDAT,
        BLART,
        BLDAT,
        GSBER,
        ZFBDT,
        BELNR
),
 
var_saida AS (
    SELECT
        BSEG_TOT.CALMONTH,
        CONTR.CSHP_CDSHOPPING,
        CONTR.INTRENO_VICNCN,
        CONTR.CC_CDCONTRATO,
        CONTR.BUKRS,
        CONTR.XWETEXT,
        CONTR.SWENR,
        CONTR.SMENR,
        CONTR.XMETXT,
        CONTR.SSTOCKW,
        CONTR.SSTCKBIS,
        CONTR.RLGESCH,
        CONTR.NTPER,
        CONTR.RECNNR,
        CONTR.RECNTYPE,
        CONTR.RECNTYPE_TEXT30,
        CONTR.RECNTXT,
        CONTR.PAVAL,
        CONTR.RECNBEG,
        CONTR.ZZREDILJ,
        CONTR.RECNENDABS,
        CONTR.CODNATPB,
        CONTR.ZZCLASS_ZNATPB,
        CONTR.ZCODREDE,
        CONTR.ZZCLASS_ZREDE,
        CONTR.ZCODABL,
        CONTR.ZZCLASS_ZGRABL,
        CONTR.ZCODABRASCE,
        CONTR.ZZCLASS_ZGRABRASCE,
        CONTR.OBJNR,
        CONTR.PARTNER_TR0200,
        CONTR.PARTNER_TR0600,
        CONTR.PARTNER_TR0605,
        CONTR.PARTNER_TR0806,
        BSEG_TOT.KUNNR,
        BSEG_TOT.HKONT,
        BSEG_TOT.UMSKZ,
        BSEG_TOT.AUGDT,
        BSEG_TOT.AUGBL,
        BSEG_TOT.AUGGJ,
        BSEG_TOT.ZUONR,
        BSEG_TOT.GJAHR,
        BSEG_TOT.BUZEI,
        BSEG_TOT.SHKZG,
        BSEG_TOT.VERTN,
        BSEG_TOT.REBZG,
        BSEG_TOT.REBZJ,
        BSEG_TOT.REBZZ,
        BSEG_TOT.BUDAT,
        BSEG_TOT.BLART,
        BSEG_TOT.BLDAT,
        BSEG_TOT.GSBER,
        BSEG_TOT.ZFBDT,
        BSEG_TOT.BELNR,
        BSEG_TOT.WRBTR,
        LEFT(BSEG_TOT.BELNR, 2) AS BELNR_AUGBL,
        CASE WHEN BSEG_TOT.CALMONTH >= IP_COMPETENCIA THEN BSEG_TOT.WRBTR 
                ELSE 0 END AS VALOR,
        CONTR.CC_DIAS_VENCTO,
        CONTR.CC_FQMFLART_SONAE, 
        CONTR.FQMFLART,
        BSEG_TOT.VLCAR_TOT AS VLCAR_TOT,	
        0 AS VLCAR_ALUG,
        0 AS VLCAR_REF,
        0 AS VLCAR_INAG,
        BSEG_TOT.VLDESC_PRE_CTO       +
        BSEG_TOT.VLDESC_PRE_ALUG      +
        BSEG_TOT.VLDESC_PRE_LOJA_TEMP +
        BSEG_TOT.VLDESC_PRE_MALL      +
        BSEG_TOT.VLDESC_PRE_COND_PAG  +
        BSEG_TOT.VLDESC_PRE_EXTRA	  +
        BSEG_TOT.VLDESC_PRE_MIDIA AS VLDESC_PRE_TOT,
        BSEG_TOT.VLDESC_PRE_CTO	AS VLDESC_PRE_CTO,
        BSEG_TOT.VLDESC_PRE_ALUG AS VLDESC_PRE_ALUG,
        BSEG_TOT.VLDESC_PRE_LOJA_TEMP AS VLDESC_PRE_LOJA_TEMP,
        BSEG_TOT.VLDESC_PRE_MALL AS VLDESC_PRE_MALL,
        BSEG_TOT.VLDESC_PRE_MIDIA AS VLDESC_PRE_MIDIA,
        0 AS VLDESC_PRE_ESTAC,
        0 AS VLDESC_PRE_LOJAS,
        BSEG_TOT.VLDESC_PRE_COND_PAG AS VLDESC_PRE_COND_PAG,
        0 AS VLDESC_PRE_INAG,
        0 AS VLDESC_PRE_ALUG_DOBRO,
        BSEG_TOT.VLDESC_PRE_EXTRA AS VLDESC_PRE_EXTRA,
        BSEG_TOT.VLDESC_POS AS VLDESC_POS_TOT,
        0 AS VLDESC_POS_LOJA,
        0 AS VLDESC_POS_MALL,
        0 AS VLDESC_POS_MIDIA,
        BSEG_TOT.VLCANCELAMENTO_TOT AS VLCANCELAMENTO_TOT,
        0 AS VLCANCELAMENTO_LOJA,
        0 AS VLCANCELAMENTO_MALL,
        0 AS VLCANCELAMENTO_MIDIA,
        0 AS VLDEVOLUCAO,
        BSEG_TOT.CC_DESCONTO_PRO AS CC_DESCONTO_PRO,
        BSEG_TOT.CC_DESCONTO_PAR AS CC_DESCONTO_PAR,
        BSEG_TOT.VLDESC_ENCARGO	AS VLDESC_ENCARGO,
        BSEG_TOT.VLDESC_FPP AS VLDESC_FPP,
        BSEG_TOT.VLDESC_POS	AS VLDESC_POS,
        BSEG_TOT.VLDESC_PERDAO_DIVIDA AS VLDESC_PERDAO_DIVIDA,
        BSEG_TOT.VLDESC_CONDICIONAL_POS_TOT AS VLDESC_CONDICIONAL_POS_TOT,
        BSEG_TOT.VLDESC_CONDICIONAL_PRE_TOT	AS VLDESC_CONDICIONAL_PRE_TOT,
        BSEG_TOT.VLDESC_CONDICIONAL_POS_TOT +
        BSEG_TOT.VLDESC_CONDICIONAL_PRE_TOT	AS VLDESC_CONDICIONAL_TOT,
        IFNULL(BSEG_TOT.FLAG_LANC_BSEG, 'N') AS FLAG_LANC_BSEG
    FROM var_contr AS CONTR
    INNER JOIN var_doc_sum AS BSEG_TOT
        ON  BSEG_TOT.BUKRS	= CONTR.BUKRS
        AND BSEG_TOT.RECNNR = CONTR.RECNNR
)

SELECT
    SAIDA.CALMONTH,
    SAIDA.CALMONTH AS CALMONTH_INT,
    SAIDA.CSHP_CDSHOPPING,
    SAIDA.INTRENO_VICNCN,
    SAIDA.CC_CDCONTRATO,
    SAIDA.BUKRS,
    SAIDA.XWETEXT,
    SAIDA.SWENR,
    SAIDA.SMENR,
    SAIDA.XMETXT,
    SAIDA.SSTOCKW,
    SAIDA.SSTCKBIS,
    SAIDA.RLGESCH,
    SAIDA.NTPER,
    SAIDA.RECNNR,
    SAIDA.RECNTYPE,
    SAIDA.RECNTYPE_TEXT30,
    SAIDA.RECNTXT,
    SAIDA.PAVAL,
    SAIDA.RECNBEG,
    SAIDA.ZZREDILJ,
    SAIDA.RECNENDABS,
    SAIDA.CODNATPB,
    SAIDA.ZZCLASS_ZNATPB,
    SAIDA.ZCODREDE,
    SAIDA.ZZCLASS_ZREDE,
    SAIDA.ZCODABL,
    SAIDA.ZZCLASS_ZGRABL,
    SAIDA.ZCODABRASCE,
    SAIDA.ZZCLASS_ZGRABRASCE,
    SAIDA.OBJNR,
    SAIDA.PARTNER_TR0200,
    SAIDA.PARTNER_TR0600,
    SAIDA.PARTNER_TR0605,
    SAIDA.PARTNER_TR0806,
    SAIDA.KUNNR,
    SAIDA.HKONT,
    SAIDA.UMSKZ,
    SAIDA.AUGDT,
    SAIDA.AUGBL,
    SAIDA.AUGGJ,
    SAIDA.ZUONR,
    SAIDA.GJAHR,
    SAIDA.BUZEI,
    SAIDA.SHKZG,
    SAIDA.VERTN,
    SAIDA.REBZG,
    SAIDA.REBZJ,
    SAIDA.REBZZ,
    SAIDA.BUDAT,
    SAIDA.BLART,
    SAIDA.BLDAT,
    SAIDA.GSBER,
    IFNULL(KONT.CC_CDTPCONTA, 5) AS CC_CDTPCONTA,
    SAIDA.ZFBDT,
    LEFT(SAIDA.ZFBDT, 6) AS ZFBDT_ANO_MES,
    SAIDA.BELNR,
    SAIDA.BELNR_AUGBL,
    SAIDA.VALOR,
    SAIDA.WRBTR,
    SAIDA.CC_DIAS_VENCTO,
    SAIDA.CC_FQMFLART_SONAE, 
    SAIDA.FQMFLART,
    SAIDA.VLCAR_TOT,	
    SAIDA.VLCAR_ALUG,
    SAIDA.VLCAR_REF,
    SAIDA.VLCAR_INAG,
    SAIDA.VLDESC_CONDICIONAL_TOT	+
    SAIDA.VLDESC_PRE_TOT			+
    SAIDA.VLDESC_POS_TOT			+
    SAIDA.VLCANCELAMENTO_TOT		+
    SAIDA.VLDESC_ENCARGO			+
    SAIDA.VLDESC_FPP				+
    SAIDA.VLCAR_TOT					+
    SAIDA.VLDESC_PERDAO_DIVIDA AS VLDESC_TOT,
    SAIDA.VLDESC_PRE_TOT,
    SAIDA.VLDESC_PRE_CTO,
    SAIDA.VLDESC_PRE_ALUG,
    SAIDA.VLDESC_PRE_LOJA_TEMP,
    SAIDA.VLDESC_PRE_MALL,
    SAIDA.VLDESC_PRE_MIDIA,
    SAIDA.VLDESC_PRE_ESTAC,
    SAIDA.VLDESC_PRE_LOJAS,
    SAIDA.VLDESC_PRE_COND_PAG,
    SAIDA.VLDESC_PRE_INAG,
    SAIDA.VLDESC_PRE_ALUG_DOBRO,
    SAIDA.VLDESC_PRE_EXTRA,
    SAIDA.VLDESC_POS_TOT,
    SAIDA.VLDESC_POS_LOJA,
    SAIDA.VLDESC_POS_MALL,
    SAIDA.VLDESC_POS_MIDIA,
    SAIDA.VLCANCELAMENTO_TOT,
    SAIDA.VLCANCELAMENTO_LOJA,
    SAIDA.VLCANCELAMENTO_MALL,
    SAIDA.VLCANCELAMENTO_MIDIA,
    SAIDA.VLDEVOLUCAO,
    SAIDA.CC_DESCONTO_PRO,
    SAIDA.CC_DESCONTO_PAR,
    SAIDA.VLDESC_ENCARGO,
    SAIDA.VLDESC_FPP,
    SAIDA.VLDESC_POS,
    SAIDA.VLDESC_PERDAO_DIVIDA,
    SAIDA.VLDESC_CONDICIONAL_POS_TOT,
    SAIDA.VLDESC_CONDICIONAL_PRE_TOT,
    SAIDA.VLDESC_CONDICIONAL_TOT,
    SAIDA.FLAG_LANC_BSEG
FROM var_saida AS SAIDA
LEFT OUTER JOIN var_hkont AS KONT
    ON KONT.HKONT = SAIDA.HKONT
)
;