CREATE OR REPLACE TABLE FUNCTION also-analytics-model-prod.2_NEGOCIO_S4.TF_OBJETO_LOCACAO_MENSAL_4B
AS 

WITH var_calmonth_min AS (
    SELECT 
        LEFT(MIN(VALIDFROM), 6) AS CALMONTH_MIN
    FROM also-analytics-model-prod.1_AQUISICAO_S4.VIBDRO
    WHERE VALIDFROM <> '00000000'
)
    
,var_calmonth AS (
    SELECT
        TEMPO_MENSAL.CALMONTH
    FROM TARGET::DIM_TEMPO_MENSAL AS TEMPO_MENSAL
    INNER JOIN var_calmonth_min AS TEMPO_MIN
        ON  TEMPO_MENSAL.CALMONTH >= TEMPO_MIN.CALMONTH_MIN
    WHERE TEMPO_MENSAL.CALMONTH <= TO_VARCHAR(ADD_YEARS(NOW(), 1), 'YYYY') || '12'
)

, var_vibdro AS (
    SELECT
        VIBDRO.INTRENO, 
        VIBDRO.BUKRS,
        VIBDRO.SWENR,
        VIBDRO.SMENR,
        VIBDRO.OBJNR,
        VIBDRO.IMKEY,
        VIBDRO.VALIDFROM,
        VIBDRO.VALIDTO,
        VIBDRO.ROTYPE,
        CASE VIBDRO.ROTYPE
            WHEN 'RU' THEN 'Unidade de locação'
            WHEN 'PS' THEN 'Pool de áreas'
            WHEN 'RS' THEN 'Área de locação'
            WHEN 'CO' THEN 'Habitação de referência'
        END AS ROTYPE_TEXT,
        VIBDRO.SNUNR,
        VIBDRO.XMETXT,
        VIBDRO.SGRNR,
        VIBDRO.SGENR,
        VIBDRO.SGEBT,
        VIBDRO.RLGESCH,
        VIBDRO.SSTCKBIS,
        VIBDRO.XSTANDNR,
        VIBDRO.SSTOCKW,
        VIBDRO.ZVENDLOC,
        CASE VIBDRO.ZVENDLOC
            WHEN 'VEND' THEN 'Vendida'
            WHEN 'LOCA' THEN 'Locável'
            ELSE ''
        END AS ZVENDLOC_TEXT,
        VIBDRO.ZPISO,
        VIBDRO.ZVENDDESC,
        VIBDRO.ZZCLASS_TP_UTIL,
        TEMPO.CALMONTH
    FROM also-analytics-model-prod.1_AQUISICAO_S4.VIBDRO AS VIBDRO
    LEFT OUTER JOIN :var_calmonth AS TEMPO
        ON  TEMPO.CALMONTH >= LEFT(VIBDRO.VALIDFROM, 6)
        AND TEMPO.CALMONTH <= LEFT(VIBDRO.VALIDTO, 6)
)

SELECT
    VIBDRO.CALMONTH,
    VIBDRO.INTRENO				AS INTRENO_VIBDRO,
    EDIFICIO.INTRENO_VIBDBU,
    EDIFICIO.INTRENO_VIBDBE,
    VIBDRO.BUKRS,
    VIBDRO.SWENR,
    VIBDRO.SMENR,
    VIBDRO.OBJNR,
    VIBDRO.IMKEY,
    VIBDRO.VALIDFROM,
    VIBDRO.VALIDTO,
    VIBDRO.ROTYPE,
    VIBDRO.ROTYPE_TEXT,
    VIBDRO.SNUNR,
    XKBEZ 						AS SNUNR_TEXT15,
    XMBEZ 						AS SNUNR_TEXT30,
    VIBDRO.XMETXT,
    VIBDRO.SGRNR,
    VIBDRO.SGENR,
    VIBDRO.SGEBT,
    VIBDRO.RLGESCH,
    VIBDRO.SSTCKBIS,
    VIBDRO.XSTANDNR,
    VIBDRO.SSTOCKW,
    CASE WHEN ZTMM004.ZZCLASS_TP_UTIL IS NULL THEN 'OUTROS'
            WHEN ZTMM004.ZZCLASS_TP_UTIL = ''	  THEN 'OUTROS'
            ELSE ZTMM004.ZZCLASS_TP_UTIL
    END AS ZZCLASS_TP_UTIL,
    VIBDRO.ZVENDLOC,
    VIBDRO.ZVENDLOC_TEXT,
    VIBDRO.ZPISO,
    VIBDRO.ZVENDDESC,
    EDIFICIO.CSHP_CDSHOPPING,
    MEDICAO.FQMFLART,
    MEDICAO.FEINS,
    MEDICAO.FQMFLART			AS CC_ABL,
    CASE WHEN ZTMM004.ZZCLASS_TP_UTIL = 'ÂNCORA'	THEN '00001'
            WHEN ZTMM004.ZZCLASS_TP_UTIL = 'MEGA LOJA'	THEN '00002'
            WHEN ZTMM004.ZZCLASS_TP_UTIL = 'SATÉLITE'	THEN '00003'
            ELSE '00099'
    END AS CDTIPOUNL
FROM var_vibdro AS VIBDRO
LEFT OUTER JOIN also-analytics-model-prod.DIM_EDIFICIO_4P
    AS EDIFICIO
    ON  EDIFICIO.BUKRS = VIBDRO.BUKRS
    AND EDIFICIO.SWENR = VIBDRO.SWENR
    AND EDIFICIO.SGENR = VIBDRO.SGENR
LEFT OUTER JOIN aliansceSonae.2_business.financerio.s4::CVW_OBJETO_LOCACAO_MEDICAO_MENSAL_4B
    AS MEDICAO
    ON  MEDICAO.INTRENO_VIBDRO = VIBDRO.INTRENO
    AND MEDICAO.CALMONTH       = VIBDRO.CALMONTH
LEFT OUTER JOIN also-analytics-model-prod.1_AQUISICAO_S4.TIV0A AS TIV0A
    ON  TIV0A.SNUNR = VIBDRO.SNUNR
    AND TIV0A.SPRAS = 'P'
LEFT OUTER JOIN also-analytics-model-prod.1_AQUISICAO_S4.ZTMM004 AS ZTMM004
    ON  ZTMM004.ZZCLASS_TP_UTIL = VIBDRO.ZZCLASS_TP_UTIL
    AND ZTMM004.SNUNR           = VIBDRO.SNUNR;
