CREATE OR REPLACE TABLE FUNCTION `also-analytics-model-nonprod.2_NEGOCIO_S4.TF_OBJETO_LOCACAO_MEDICAO_MENSAL_4B`() 
AS
WITH var_objloc AS ( 
    SELECT 
        INTRENO AS INTRENO_VIBDRO,
        CASE WHEN VALIDFROM IS NULL			THEN "2021-01-01"
                WHEN VALIDFROM = ''				THEN "2021-01-01"
                WHEN CAST(VALIDFROM AS INT64) <	20210101	THEN "2021-01-01"
                ELSE VALIDFROM
        END AS VALIDFROM,
        CASE WHEN VALIDTO IS NULL THEN "2031-01-01"
                WHEN VALIDTO = '' THEN "2031-01-01"
                WHEN CAST(VALIDTO AS INT64) > 20310101 THEN "2031-01-01"
                ELSE VALIDTO
        END AS VALIDTO
    FROM `also-analytics-model-nonprod.1_AQUISICAO_S4.vibdro`
),
               
var_objloc_tempo AS (
    SELECT 
        OBJLOC.INTRENO_VIBDRO,
        TEMPO.CALMONTH,
        OBJLOC.VALIDFROM,
        OBJLOC.VALIDTO
    FROM var_objloc AS OBJLOC
    INNER JOIN `also-analytics-model-nonprod.1_AQUISICAO_MXM.dim_tempo_mensal` AS TEMPO
        ON  LEFT(OBJLOC.VALIDFROM, 6) <= TEMPO.CALMONTH
        AND LEFT(OBJLOC.VALIDTO, 6) >= TEMPO.CALMONTH 
    WHERE TEMPO.CALMONTH BETWEEN "202101" AND "203101"
),
    
var_vibdmeas AS (
    SELECT 
        INTRENO,
        MEAS,
        VALIDTO,
        CASE WHEN VALIDFROM IS NULL	THEN "2021-01-01"
                WHEN VALIDFROM = ''		THEN "2021-01-01"
                ELSE VALIDFROM
        END AS VALIDFROM,
        MEASVALUE,
        MEASUNIT
    FROM `also-analytics-model-nonprod.1_AQUISICAO_S4.vibdmeas`
    WHERE INTRENO IN (SELECT INTRENO_VIBDRO FROM var_objloc_tempo GROUP BY INTRENO_VIBDRO)
),
       
var_vibdmeas_tempo AS (
    SELECT 
        VIBDMEAS.INTRENO,
        TEMPO.CALMONTH,
        VIBDMEAS.VALIDFROM,
        VIBDMEAS.VALIDTO,
        VIBDMEAS.MEAS,
        VIBDMEAS.MEASVALUE,
        VIBDMEAS.MEASUNIT
    FROM var_vibdmeas AS VIBDMEAS
    INNER JOIN `also-analytics-model-nonprod.1_AQUISICAO_MXM.dim_tempo_mensal` AS TEMPO
        ON  LEFT(VIBDMEAS.VALIDFROM, 6) <= TEMPO.CALMONTH
        AND LEFT(VIBDMEAS.VALIDTO, 6) >= TEMPO.CALMONTH 
    WHERE TEMPO.CALMONTH BETWEEN "202101" AND "203101"
)
 
SELECT
    VIBDRO.INTRENO_VIBDRO,
    VIBDRO.CALMONTH,
    MAX(VIBDMEAS_Z009.MEASVALUE) 	AS MEASVALUE_Z009,
    MAX(VIBDMEAS_Z009.MEASUNIT)  	AS MEASUNIT_Z009,
    MAX(VIBDMEAS_Z009.MEASVALUE) 	AS MEASVALUE_Z010,
    MAX(VIBDMEAS_Z009.MEASUNIT)  	AS MEASUNIT_Z010,
    MAX(VIBDMEAS_Z012.MEASVALUE) 	AS MEASVALUE_Z012,
    MAX(VIBDMEAS_Z012.MEASUNIT)  	AS MEASUNIT_Z012,
    MAX(VIBDMEAS_ZA03.MEASVALUE) 	AS MEASVALUE_ZA03,
    MAX(VIBDMEAS_ZA03.MEASUNIT)  	AS MEASUNIT_ZA03,
    MAX(VIBDMEAS_ZA08.MEASVALUE) 	AS MEASVALUE_ZA08,
    MAX(VIBDMEAS_ZA08.MEASUNIT)  	AS MEASUNIT_ZA08,
    MAX(VIBDMEAS_ZA10.MEASVALUE) 	AS MEASVALUE_ZA10,
    MAX(VIBDMEAS_ZA10.MEASUNIT)  	AS MEASUNIT_ZA10,
    MAX(VIBDMEAS_ZA16.MEASVALUE) 	AS MEASVALUE_ZA16,
    MAX(VIBDMEAS_ZA16.MEASUNIT)  	AS MEASUNIT_ZA16,
    MAX(VIBDMEAS_ZD01.MEASVALUE) 	AS MEASVALUE_ZD01,
    MAX(VIBDMEAS_ZD01.MEASUNIT)  	AS MEASUNIT_ZD01,
    MAX(VIBDMEAS_ZD02.MEASVALUE) 	AS MEASVALUE_ZD02,
    MAX(VIBDMEAS_ZD02.MEASUNIT)  	AS MEASUNIT_ZD02,
    MAX(VIBDMEAS_ZD03.MEASVALUE) 	AS MEASVALUE_ZD03,
    MAX(VIBDMEAS_ZD03.MEASUNIT)  	AS MEASUNIT_ZD03,
    MAX(VIBDMEAS_ZD04.MEASVALUE) 	AS MEASVALUE_ZD04,
    MAX(VIBDMEAS_ZD04.MEASUNIT)  	AS MEASUNIT_ZD04,
    MAX(VIBDMEAS_ZD05.MEASVALUE) 	AS MEASVALUE_ZD05,
    MAX(VIBDMEAS_ZD05.MEASUNIT)  	AS MEASUNIT_ZD05,
    MAX(VIBDMEAS_ZD06.MEASVALUE) 	AS MEASVALUE_ZD06,
    MAX(VIBDMEAS_ZD06.MEASUNIT)  	AS MEASUNIT_ZD06,
    MAX(VIBDMEAS_ZE01.MEASVALUE) 	AS MEASVALUE_ZE01,
    MAX(VIBDMEAS_ZE01.MEASUNIT)  	AS MEASUNIT_ZE01,
    MAX(VIBDMEAS_ZE02.MEASVALUE) 	AS MEASVALUE_ZE02,
    MAX(VIBDMEAS_ZE02.MEASUNIT)  	AS MEASUNIT_ZE02,
    MAX(VIBDMEAS_ZE03.MEASVALUE) 	AS MEASVALUE_ZE03,
    MAX(VIBDMEAS_ZE03.MEASUNIT)  	AS MEASUNIT_ZE03,
    MAX(VIBDMEAS_ZE04.MEASVALUE) 	AS MEASVALUE_ZE04,
    MAX(VIBDMEAS_ZE04.MEASUNIT)  	AS MEASUNIT_ZE04,
    MAX(VIBDMEAS_ZE05.MEASVALUE) 	AS MEASVALUE_ZE05,
    MAX(VIBDMEAS_ZE05.MEASUNIT)  	AS MEASUNIT_ZE05,
    MAX(VIBDMEAS_ZE06.MEASVALUE) 	AS MEASVALUE_ZE06,
    MAX(VIBDMEAS_ZE06.MEASUNIT)  	AS MEASUNIT_ZE06,
    MAX(VIBDMEAS_ZE07.MEASVALUE) 	AS MEASVALUE_ZE07,
    MAX(VIBDMEAS_ZE07.MEASUNIT)  	AS MEASUNIT_ZE07,
    MAX(VIBDMEAS_ZE08.MEASVALUE) 	AS MEASVALUE_ZE08,
    MAX(VIBDMEAS_ZE08.MEASUNIT)  	AS MEASUNIT_ZE08,
    MAX(VIBDMEAS_ZE10.MEASVALUE) 	AS MEASVALUE_ZE10,
    MAX(VIBDMEAS_ZE10.MEASUNIT)  	AS MEASUNIT_ZE10,
    MAX(VIBDMEAS_ZE11.MEASVALUE) 	AS MEASVALUE_ZE11,
    MAX(VIBDMEAS_ZE11.MEASUNIT)  	AS MEASUNIT_ZE11,
    MAX(VIBDMEAS_ZE12.MEASVALUE) 	AS MEASVALUE_ZE12,
    MAX(VIBDMEAS_ZE12.MEASUNIT)  	AS MEASUNIT_ZE12,
    MAX(VIBDMEAS_ZE13.MEASVALUE) 	AS MEASVALUE_ZE13,
    MAX(VIBDMEAS_ZE13.MEASUNIT)  	AS MEASUNIT_ZE13,
    MAX(VIBDMEAS_ZE14.MEASVALUE) 	AS MEASVALUE_ZE14,
    MAX(VIBDMEAS_ZE14.MEASUNIT)  	AS MEASUNIT_ZE14,
    MAX(VIBDMEAS_ZE15.MEASVALUE) 	AS MEASVALUE_ZE15,
    MAX(VIBDMEAS_ZE15.MEASUNIT)  	AS MEASUNIT_ZE15,
    MAX(VIBDMEAS_ZE16.MEASVALUE) 	AS MEASVALUE_ZE16,
    MAX(VIBDMEAS_ZE16.MEASUNIT)  	AS MEASUNIT_ZE16,
    MAX(VIBDMEAS_ZE17.MEASVALUE) 	AS MEASVALUE_ZE17,
    MAX(VIBDMEAS_ZE17.MEASUNIT)  	AS MEASUNIT_ZE17,
    MAX(VIBDMEAS_ZE18.MEASVALUE) 	AS MEASVALUE_ZE18,
    MAX(VIBDMEAS_ZE18.MEASUNIT)  	AS MEASUNIT_ZE18,
    MAX(VIBDMEAS_ZF01.MEASVALUE) 	AS MEASVALUE_ZF01,
    MAX(VIBDMEAS_ZF01.MEASUNIT)  	AS MEASUNIT_ZF01,
    MAX(VIBDMEAS_ZF02.MEASVALUE) 	AS MEASVALUE_ZF02,
    MAX(VIBDMEAS_ZF02.MEASUNIT)  	AS MEASUNIT_ZF02,
    MAX(VIBDMEAS_ZF03.MEASVALUE) 	AS MEASVALUE_ZF03,
    MAX(VIBDMEAS_ZF03.MEASUNIT)  	AS MEASUNIT_ZF03,
    MAX(VIBDMEAS_ZF04.MEASVALUE) 	AS MEASVALUE_ZF04,
    MAX(VIBDMEAS_ZF04.MEASUNIT)  	AS MEASUNIT_ZF04,
    MAX(VIBDMEAS_ZT02.MEASVALUE) 	AS MEASVALUE_ZT02,
    MAX(VIBDMEAS_ZT02.MEASUNIT)  	AS MEASUNIT_ZT02,
    CASE WHEN MAX(VIBDMEAS_Z009.MEASVALUE) IS NOT NULL THEN MAX(VIBDMEAS_Z009.MEASVALUE)
            WHEN MAX(VIBDMEAS_Z010.MEASVALUE) IS NOT NULL THEN MAX(VIBDMEAS_Z010.MEASVALUE)
            WHEN MAX(VIBDMEAS_ZA03.MEASVALUE) IS NOT NULL THEN MAX(VIBDMEAS_ZA03.MEASVALUE)
            WHEN MAX(VIBDMEAS_ZA08.MEASVALUE) IS NOT NULL THEN MAX(VIBDMEAS_ZA08.MEASVALUE)
            WHEN MAX(VIBDMEAS_ZA10.MEASVALUE) IS NOT NULL THEN MAX(VIBDMEAS_ZA10.MEASVALUE)
            WHEN MAX(VIBDMEAS_ZA16.MEASVALUE) IS NOT NULL THEN MAX(VIBDMEAS_ZA16.MEASVALUE)
            WHEN MAX(VIBDMEAS_ZD04.MEASVALUE) IS NOT NULL THEN MAX(VIBDMEAS_ZD04.MEASVALUE)
            WHEN MAX(VIBDMEAS_ZD05.MEASVALUE) IS NOT NULL THEN MAX(VIBDMEAS_ZD05.MEASVALUE)
            WHEN MAX(VIBDMEAS_ZE01.MEASVALUE) IS NOT NULL THEN MAX(VIBDMEAS_ZE01.MEASVALUE)
            WHEN MAX(VIBDMEAS_ZE02.MEASVALUE) IS NOT NULL THEN MAX(VIBDMEAS_ZE02.MEASVALUE)
            WHEN MAX(VIBDMEAS_ZT02.MEASVALUE) IS NOT NULL THEN MAX(VIBDMEAS_ZT02.MEASVALUE)
            ELSE 0
    END AS FQMFLART,
    CASE WHEN MAX(VIBDMEAS_Z009.MEASUNIT) IS NOT NULL THEN MAX(VIBDMEAS_Z009.MEASUNIT)
            WHEN MAX(VIBDMEAS_Z010.MEASUNIT) IS NOT NULL THEN MAX(VIBDMEAS_Z010.MEASUNIT)
            WHEN MAX(VIBDMEAS_ZA03.MEASUNIT) IS NOT NULL THEN MAX(VIBDMEAS_ZA03.MEASUNIT)
            WHEN MAX(VIBDMEAS_ZA08.MEASUNIT) IS NOT NULL THEN MAX(VIBDMEAS_ZA08.MEASUNIT)
            WHEN MAX(VIBDMEAS_ZA10.MEASUNIT) IS NOT NULL THEN MAX(VIBDMEAS_ZA10.MEASUNIT)
            WHEN MAX(VIBDMEAS_ZA16.MEASUNIT) IS NOT NULL THEN MAX(VIBDMEAS_ZA16.MEASUNIT)
            WHEN MAX(VIBDMEAS_ZD04.MEASUNIT) IS NOT NULL THEN MAX(VIBDMEAS_ZD04.MEASUNIT)
            WHEN MAX(VIBDMEAS_ZD05.MEASUNIT) IS NOT NULL THEN MAX(VIBDMEAS_ZD05.MEASUNIT)
            WHEN MAX(VIBDMEAS_ZE01.MEASUNIT) IS NOT NULL THEN MAX(VIBDMEAS_ZE01.MEASUNIT)
            WHEN MAX(VIBDMEAS_ZE02.MEASUNIT) IS NOT NULL THEN MAX(VIBDMEAS_ZE02.MEASUNIT)
            WHEN MAX(VIBDMEAS_ZT02.MEASUNIT) IS NOT NULL THEN MAX(VIBDMEAS_ZT02.MEASUNIT)
            ELSE 'M2'
    END AS FEINS
FROM var_objloc_tempo AS VIBDRO
LEFT OUTER JOIN var_vibdmeas_tempo AS VIBDMEAS_Z009
    ON 	VIBDMEAS_Z009.CALMONTH = VIBDRO.CALMONTH
    AND VIBDMEAS_Z009.INTRENO  = VIBDRO.INTRENO_VIBDRO
    AND VIBDMEAS_Z009.MEAS     = 'Z009'
LEFT OUTER JOIN var_vibdmeas_tempo AS VIBDMEAS_Z010
    ON 	VIBDMEAS_Z010.CALMONTH = VIBDRO.CALMONTH
    AND VIBDMEAS_Z010.INTRENO  = VIBDRO.INTRENO_VIBDRO
    AND VIBDMEAS_Z010.MEAS     = 'Z010'
LEFT OUTER JOIN var_vibdmeas_tempo AS VIBDMEAS_Z012
    ON 	VIBDMEAS_Z012.CALMONTH = VIBDRO.CALMONTH
    AND VIBDMEAS_Z012.INTRENO  = VIBDRO.INTRENO_VIBDRO
    AND VIBDMEAS_Z012.MEAS     = 'Z012'
LEFT OUTER JOIN var_vibdmeas_tempo AS VIBDMEAS_ZA03
    ON 	VIBDMEAS_ZA03.CALMONTH = VIBDRO.CALMONTH
    AND VIBDMEAS_ZA03.INTRENO  = VIBDRO.INTRENO_VIBDRO
    AND VIBDMEAS_ZA03.MEAS     = 'ZA03'
LEFT OUTER JOIN var_vibdmeas_tempo AS VIBDMEAS_ZA08
    ON 	VIBDMEAS_ZA08.CALMONTH = VIBDRO.CALMONTH
    AND VIBDMEAS_ZA08.INTRENO  = VIBDRO.INTRENO_VIBDRO
    AND VIBDMEAS_ZA08.MEAS     = 'ZA08'
LEFT OUTER JOIN var_vibdmeas_tempo AS VIBDMEAS_ZA10
    ON 	VIBDMEAS_ZA10.CALMONTH = VIBDRO.CALMONTH
    AND VIBDMEAS_ZA10.INTRENO  = VIBDRO.INTRENO_VIBDRO
    AND VIBDMEAS_ZA10.MEAS     = 'ZA10'
LEFT OUTER JOIN var_vibdmeas_tempo AS VIBDMEAS_ZA16
    ON 	VIBDMEAS_ZA16.CALMONTH = VIBDRO.CALMONTH
    AND VIBDMEAS_ZA16.INTRENO  = VIBDRO.INTRENO_VIBDRO
    AND VIBDMEAS_ZA16.MEAS     = 'ZA16'
LEFT OUTER JOIN var_vibdmeas_tempo AS VIBDMEAS_ZD01
    ON 	VIBDMEAS_ZD01.CALMONTH = VIBDRO.CALMONTH
    AND VIBDMEAS_ZD01.INTRENO  = VIBDRO.INTRENO_VIBDRO
    AND VIBDMEAS_ZD01.MEAS     = 'ZD01'
LEFT OUTER JOIN var_vibdmeas_tempo AS VIBDMEAS_ZD02
    ON 	VIBDMEAS_ZD02.CALMONTH = VIBDRO.CALMONTH
    AND VIBDMEAS_ZD02.INTRENO  = VIBDRO.INTRENO_VIBDRO
    AND VIBDMEAS_ZD02.MEAS     = 'ZD02'
LEFT OUTER JOIN var_vibdmeas_tempo AS VIBDMEAS_ZD03
    ON 	VIBDMEAS_ZD03.CALMONTH = VIBDRO.CALMONTH
    AND VIBDMEAS_ZD03.INTRENO  = VIBDRO.INTRENO_VIBDRO
    AND VIBDMEAS_ZD03.MEAS     = 'ZD03'
LEFT OUTER JOIN var_vibdmeas_tempo AS VIBDMEAS_ZD04
    ON 	VIBDMEAS_ZD04.CALMONTH = VIBDRO.CALMONTH
    AND VIBDMEAS_ZD04.INTRENO  = VIBDRO.INTRENO_VIBDRO
    AND VIBDMEAS_ZD04.MEAS     = 'ZD04'
LEFT OUTER JOIN var_vibdmeas_tempo AS VIBDMEAS_ZD05
    ON 	VIBDMEAS_ZD05.CALMONTH = VIBDRO.CALMONTH
    AND VIBDMEAS_ZD05.INTRENO  = VIBDRO.INTRENO_VIBDRO
    AND VIBDMEAS_ZD05.MEAS     = 'ZD05'
LEFT OUTER JOIN var_vibdmeas_tempo AS VIBDMEAS_ZD06
    ON 	VIBDMEAS_ZD06.CALMONTH = VIBDRO.CALMONTH
    AND VIBDMEAS_ZD06.INTRENO  = VIBDRO.INTRENO_VIBDRO
    AND VIBDMEAS_ZD06.MEAS     = 'ZD06'
LEFT OUTER JOIN var_vibdmeas_tempo AS VIBDMEAS_ZE01
    ON 	VIBDMEAS_ZE01.CALMONTH = VIBDRO.CALMONTH
    AND VIBDMEAS_ZE01.INTRENO  = VIBDRO.INTRENO_VIBDRO
    AND VIBDMEAS_ZE01.MEAS     = 'ZE01'
LEFT OUTER JOIN var_vibdmeas_tempo AS VIBDMEAS_ZE02
    ON 	VIBDMEAS_ZE02.CALMONTH = VIBDRO.CALMONTH
    AND VIBDMEAS_ZE02.INTRENO  = VIBDRO.INTRENO_VIBDRO
    AND VIBDMEAS_ZE02.MEAS     = 'ZE02'
LEFT OUTER JOIN var_vibdmeas_tempo AS VIBDMEAS_ZE03
    ON 	VIBDMEAS_ZE03.CALMONTH = VIBDRO.CALMONTH
    AND VIBDMEAS_ZE03.INTRENO  = VIBDRO.INTRENO_VIBDRO
    AND VIBDMEAS_ZE03.MEAS     = 'ZE03'
LEFT OUTER JOIN var_vibdmeas_tempo AS VIBDMEAS_ZE04
    ON 	VIBDMEAS_ZE04.CALMONTH = VIBDRO.CALMONTH
    AND VIBDMEAS_ZE04.INTRENO  = VIBDRO.INTRENO_VIBDRO
    AND VIBDMEAS_ZE04.MEAS     = 'ZE04'
LEFT OUTER JOIN var_vibdmeas_tempo AS VIBDMEAS_ZE05
    ON 	VIBDMEAS_ZE05.CALMONTH = VIBDRO.CALMONTH
    AND VIBDMEAS_ZE05.INTRENO  = VIBDRO.INTRENO_VIBDRO
    AND VIBDMEAS_ZE05.MEAS     = 'ZE05'
LEFT OUTER JOIN var_vibdmeas_tempo AS VIBDMEAS_ZE06
    ON 	VIBDMEAS_ZE06.CALMONTH = VIBDRO.CALMONTH
    AND VIBDMEAS_ZE06.INTRENO  = VIBDRO.INTRENO_VIBDRO
    AND VIBDMEAS_ZE06.MEAS     = 'ZE06'
LEFT OUTER JOIN var_vibdmeas_tempo AS VIBDMEAS_ZE07
    ON 	VIBDMEAS_ZE07.CALMONTH = VIBDRO.CALMONTH
    AND VIBDMEAS_ZE07.INTRENO  = VIBDRO.INTRENO_VIBDRO
    AND VIBDMEAS_ZE07.MEAS     = 'ZE07'
LEFT OUTER JOIN var_vibdmeas_tempo AS VIBDMEAS_ZE08
    ON 	VIBDMEAS_ZE08.CALMONTH = VIBDRO.CALMONTH
    AND VIBDMEAS_ZE08.INTRENO  = VIBDRO.INTRENO_VIBDRO
    AND VIBDMEAS_ZE08.MEAS     = 'ZE08'
LEFT OUTER JOIN var_vibdmeas_tempo AS VIBDMEAS_ZE10
    ON 	VIBDMEAS_ZE10.CALMONTH = VIBDRO.CALMONTH
    AND VIBDMEAS_ZE10.INTRENO  = VIBDRO.INTRENO_VIBDRO
    AND VIBDMEAS_ZE10.MEAS     = 'ZE10'
LEFT OUTER JOIN var_vibdmeas_tempo AS VIBDMEAS_ZE11
    ON 	VIBDMEAS_ZE11.CALMONTH = VIBDRO.CALMONTH
    AND VIBDMEAS_ZE11.INTRENO  = VIBDRO.INTRENO_VIBDRO
    AND VIBDMEAS_ZE11.MEAS     = 'ZE11'
LEFT OUTER JOIN var_vibdmeas_tempo AS VIBDMEAS_ZE12
    ON 	VIBDMEAS_ZE12.CALMONTH = VIBDRO.CALMONTH
    AND VIBDMEAS_ZE12.INTRENO  = VIBDRO.INTRENO_VIBDRO
    AND VIBDMEAS_ZE12.MEAS     = 'ZE12'
LEFT OUTER JOIN var_vibdmeas_tempo AS VIBDMEAS_ZE13
    ON 	VIBDMEAS_ZE13.CALMONTH = VIBDRO.CALMONTH
    AND VIBDMEAS_ZE13.INTRENO  = VIBDRO.INTRENO_VIBDRO
    AND VIBDMEAS_ZE13.MEAS     = 'ZE13'
LEFT OUTER JOIN var_vibdmeas_tempo AS VIBDMEAS_ZE14
    ON 	VIBDMEAS_ZE14.CALMONTH = VIBDRO.CALMONTH
    AND VIBDMEAS_ZE14.INTRENO  = VIBDRO.INTRENO_VIBDRO
    AND VIBDMEAS_ZE14.MEAS     = 'ZE14'
LEFT OUTER JOIN var_vibdmeas_tempo AS VIBDMEAS_ZE15
    ON 	VIBDMEAS_ZE15.CALMONTH = VIBDRO.CALMONTH
    AND VIBDMEAS_ZE15.INTRENO  = VIBDRO.INTRENO_VIBDRO
    AND VIBDMEAS_ZE15.MEAS     = 'ZE15'
LEFT OUTER JOIN var_vibdmeas_tempo AS VIBDMEAS_ZE16
    ON 	VIBDMEAS_ZE16.CALMONTH = VIBDRO.CALMONTH
    AND VIBDMEAS_ZE16.INTRENO  = VIBDRO.INTRENO_VIBDRO
    AND VIBDMEAS_ZE16.MEAS     = 'ZE16'
LEFT OUTER JOIN var_vibdmeas_tempo AS VIBDMEAS_ZE17
    ON 	VIBDMEAS_ZE17.CALMONTH = VIBDRO.CALMONTH
    AND VIBDMEAS_ZE17.INTRENO  = VIBDRO.INTRENO_VIBDRO
    AND VIBDMEAS_ZE17.MEAS     = 'ZE17'
LEFT OUTER JOIN var_vibdmeas_tempo AS VIBDMEAS_ZE18
    ON 	VIBDMEAS_ZE18.CALMONTH = VIBDRO.CALMONTH
    AND VIBDMEAS_ZE18.INTRENO  = VIBDRO.INTRENO_VIBDRO
    AND VIBDMEAS_ZE18.MEAS     = 'ZE18'
LEFT OUTER JOIN var_vibdmeas_tempo AS VIBDMEAS_ZF01
    ON 	VIBDMEAS_ZF01.CALMONTH = VIBDRO.CALMONTH
    AND VIBDMEAS_ZF01.INTRENO  = VIBDRO.INTRENO_VIBDRO
    AND VIBDMEAS_ZF01.MEAS     = 'ZF01'
LEFT OUTER JOIN var_vibdmeas_tempo AS VIBDMEAS_ZF02
    ON 	VIBDMEAS_ZF02.CALMONTH = VIBDRO.CALMONTH
    AND VIBDMEAS_ZF02.INTRENO  = VIBDRO.INTRENO_VIBDRO
    AND VIBDMEAS_ZF02.MEAS     = 'ZF02'
LEFT OUTER JOIN var_vibdmeas_tempo AS VIBDMEAS_ZF03
    ON 	VIBDMEAS_ZF03.CALMONTH = VIBDRO.CALMONTH
    AND VIBDMEAS_ZF03.INTRENO  = VIBDRO.INTRENO_VIBDRO
    AND VIBDMEAS_ZF03.MEAS     = 'ZF03'
LEFT OUTER JOIN var_vibdmeas_tempo AS VIBDMEAS_ZF04
    ON 	VIBDMEAS_ZF04.CALMONTH = VIBDRO.CALMONTH
    AND VIBDMEAS_ZF04.INTRENO  = VIBDRO.INTRENO_VIBDRO
    AND VIBDMEAS_ZF04.MEAS     = 'ZF04'
LEFT OUTER JOIN var_vibdmeas_tempo AS VIBDMEAS_ZT02
    ON 	VIBDMEAS_ZT02.CALMONTH = VIBDRO.CALMONTH
    AND VIBDMEAS_ZT02.INTRENO  = VIBDRO.INTRENO_VIBDRO
    AND VIBDMEAS_ZT02.MEAS     = 'ZT02'
GROUP BY
    VIBDRO.INTRENO_VIBDRO,
    VIBDRO.CALMONTH
