CREATE OR REPLACE TABLE FUNCTION `also-analytics-model-nonprod.2_NEGOCIO_S4.TF_PARCELAMENTO_4B` () AS (

WITH var_saida AS (
    SELECT
        BKPF.GJAHR || BKPF.MONAT AS CALMONTH,
        PAR.ID,
        PAR.BUKRS,
        PAR.BELNR,
        PAR.GJAHR,
        PAR.BUZEI,
        PAR.DATA_PROR,
        PAR.CALC_CM,
        PAR.PARC,
        PAR.AGRUPA,
        PAR.PERD,
        PAR.WRBTR,
        PAR.JUROS,
        PAR.MULTA,
        PAR.COR_MONET,
        PAR.DESCONTO,
        PAR.VLR_LIQUIDO,
        PAR.DESCONTO_COND,
        BSEG.VERTN,
        BSEG.ZUONR,
        BSEG.VERTN AS CC_VERTN,
        BSEG.ZUONR AS CC_ZUONR,
        CASE WHEN LEFT(PAR.BELNR, 2) = '27' THEN IFNULL(PAR.VLR_LIQUIDO, 0) ELSE PAR.WRBTR END AS CC_DESCONTO_PAR,
        BSEG.SHKZG
    FROM `also-analytics-model-nonprod.1_AQUISICAO_S4.ztfi021_hist_par` AS PAR
    LEFT OUTER JOIN `also-analytics-model-nonprod.1_AQUISICAO_S4.bseg` AS BSEG
        ON  BSEG.BUKRS = PAR.BUKRS
        AND BSEG.BELNR = PAR.BELNR
        AND BSEG.GJAHR = PAR.GJAHR
        AND BSEG.BUZEI = PAR.BUZEI
    INNER JOIN `also-analytics-model-nonprod.1_AQUISICAO_S4.bkpf` AS BKPF
        ON  BKPF.BUKRS = BSEG.BUKRS
        AND BKPF.BELNR = BSEG.BELNR
        AND BKPF.GJAHR = BSEG.GJAHR
)

SELECT
    SAIDA.CALMONTH,
    CONTR.CSHP_CDSHOPPING,
    CONTR.INTRENO_VICNCN,
    CONTR.CC_CDCONTRATO,
    CONTR.RECNNR,
    SAIDA.ID,
    SAIDA.BUKRS,
    SAIDA.BELNR,
    SAIDA.GJAHR,
    SAIDA.BUZEI,
    SAIDA.DATA_PROR,
    SAIDA.CALC_CM,
    SAIDA.PARC,
    SAIDA.AGRUPA,
    SAIDA.PERD,
    SAIDA.WRBTR,
    SAIDA.JUROS,
    SAIDA.MULTA,
    SAIDA.COR_MONET,
    SAIDA.DESCONTO,
    SAIDA.VLR_LIQUIDO,
    SAIDA.DESCONTO_COND,
    SAIDA.VERTN,
    SAIDA.ZUONR,
    SAIDA.CC_DESCONTO_PAR,
    SAIDA.SHKZG
FROM var_saida AS SAIDA
LEFT OUTER JOIN `also-analytics-model-nonprod.3_MATERIALIZADO_S4.DIM_CONTRATO` AS CONTR
    ON CONTR.BUKRS = SAIDA.BUKRS
    AND (CONTR.RECNNR = SAIDA.CC_VERTN OR CONTR.RECNNR = SAIDA.CC_ZUONR)
)
;