CREATE OR REPLACE TABLE FUNCTION `also-analytics-model-nonprod.2_NEGOCIO_S4.TF_PRORROGACAO_4B` () AS (

WITH var_saida AS (
		SELECT
			 BKPF.GJAHR || BKPF.MONAT AS CALMONTH,
			 PRO.ID,
			 PRO.BUKRS,
			 PRO.BELNR,
			 PRO.GJAHR,
			 PRO.BUZEI,
			 PRO.BELNR_ORIG,
			 PRO.GJAHR_ORIG,
			 PRO.BUZEI_ORIG,
			 PRO.WRBTR,
			 PRO.JUROS,
			 PRO.MULTA,
			 PRO.COR_MONET,
			 PRO.DESCONTO,
			 PRO.VLR_LIQUIDO,
			 PRO.DESCONTO_COND,
			 PRO.DATA_ORIG,
			 PRO.DATA_PROR,
			 PRO.ST_WF,
			 BSEG.VERTN,
			 BSEG_ORIG.VERTN AS VERTN_ORIG,
			 BSEG.ZUONR,
			 BSEG_ORIG.ZUONR AS ZUONR_ORIG,
			 CASE WHEN IFNULL(BSEG.VERTN, '') = '' 
				THEN BSEG_ORIG.VERTN
				ELSE BSEG.VERTN
			 END 					AS CC_VERTN,
			 CASE WHEN IFNULL(BSEG.ZUONR, '') = '' 
				THEN BSEG_ORIG.ZUONR
				ELSE BSEG.ZUONR
			END 					AS CC_ZUONR,
			CASE WHEN LEFT(PRO.BELNR, 2) = '27' THEN IFNULL(PRO.VLR_LIQUIDO, 0) ELSE PRO.WRBTR END AS CC_DESCONTO_PRO,
			BSEG.SHKZG
		FROM `also-analytics-model-nonprod.1_AQUISICAO_S4.ztfi012_hist_pro` AS PRO
		LEFT OUTER JOIN `also-analytics-model-nonprod.1_AQUISICAO_S4.bseg` AS BSEG
			ON  BSEG.BUKRS = PRO.BUKRS
			AND BSEG.BELNR = PRO.BELNR
			AND BSEG.GJAHR = PRO.GJAHR
			AND BSEG.BUZEI = PRO.BUZEI
		LEFT OUTER JOIN `also-analytics-model-nonprod.1_AQUISICAO_S4.bseg` AS BSEG_ORIG
			ON  BSEG_ORIG.BUKRS = PRO.BUKRS
			AND BSEG_ORIG.BELNR = PRO.BELNR
			AND BSEG_ORIG.GJAHR = PRO.GJAHR
			AND BSEG_ORIG.BUZEI = PRO.BUZEI
		INNER JOIN `also-analytics-model-nonprod.1_AQUISICAO_S4.bkpf` AS BKPF
			ON  BKPF.BUKRS = BSEG.BUKRS
			AND BKPF.BELNR = BSEG.BELNR
			AND BKPF.GJAHR = BSEG.GJAHR
)

SELECT
        SAIDA.CALMONTH,
        CONTR.CSHP_CDSHOPPING,
        CONTR.INTRENO_VICNCN,
        CONTR.CC_CDCONTRATO,
        CONTR.RECNNR,
        SAIDA.ID,
        SAIDA.BUKRS,
        SAIDA.BELNR,
        SAIDA.GJAHR,
        SAIDA.BUZEI,
        SAIDA.BELNR_ORIG,
        SAIDA.GJAHR_ORIG,
        SAIDA.BUZEI_ORIG,
        SAIDA.WRBTR,
        SAIDA.JUROS,
        SAIDA.MULTA,
        SAIDA.COR_MONET,
        SAIDA.DESCONTO,
        SAIDA.VLR_LIQUIDO,
        SAIDA.DESCONTO_COND,
        SAIDA.DATA_ORIG,
        SAIDA.DATA_PROR,
        SAIDA.ST_WF,
        SAIDA.VERTN,
        SAIDA.VERTN_ORIG,
        SAIDA.ZUONR,
        SAIDA.ZUONR_ORIG,
        SAIDA.CC_DESCONTO_PRO,
        SAIDA.SHKZG
FROM var_saida AS SAIDA
LEFT OUTER JOIN `also-analytics-model-nonprod.3_MATERIALIZADO_S4.DIM_CONTRATO` AS CONTR
    ON  CONTR.BUKRS   = SAIDA.BUKRS
    AND (CONTR.RECNNR = SAIDA.CC_VERTN OR CONTR.RECNNR = SAIDA.CC_ZUONR)
)
;