CREATE OR REPLACE TABLE FUNCTION `also-analytics-model-nonprod.2_NEGOCIO_S4.TF_SHOPPING_4B` ()

AS 
	
SELECT
    VIBDBE.INTRENO			AS INTRENO_VIBDBE, 
    VIBDBE.BUKRS			AS BUKRS,
    VIBDBE.SWENR			AS SWENR_VIBDBE,
    VIBDBE.XWETEXT			AS XWETEXT,
    CASE WHEN VIBDBE.SWENR IN ('AAA','BBB')			THEN 'SSA'
            WHEN VIBDBE.SWENR IN ('HHH')				THEN 'III'
            WHEN VIBDBE.SWENR IN ('EEE','QQQ')			THEN 'GGG'
            WHEN VIBDBE.SWENR IN ('SSS','DDD')			THEN 'FFF'
            WHEN VIBDBE.SWENR IN ('REPLICA')			THEN 'SH80'
            WHEN VIBDBE.SWENR IN ('MTR')				THEN 'SH02'
            WHEN VIBDBE.SWENR IN ('PDP')				THEN 'SH06'
            WHEN VIBDBE.SWENR IN ('PSS')				THEN 'SH08'
            WHEN VIBDBE.SWENR IN ('SCL')				THEN 'SH09'
            WHEN VIBDBE.SWENR IN ('MAN')				THEN 'SH10'
            WHEN VIBDBE.SWENR IN ('BLS')				THEN 'SH11'
            WHEN VIBDBE.SWENR IN ('PAS')				THEN 'SH12'
            WHEN VIBDBE.SWENR IN ('FRANCA','UBE')		THEN 'SH13'
            WHEN VIBDBE.SWENR IN ('STB')				THEN 'TDS'
            WHEN VIBDBE.SWENR IN ('BBA')				THEN 'SNB'
            WHEN VIBDBE.SWENR IN ('SBA01')				THEN 'NAC'
            WHEN VIBDBE.SWENR IN ('SBA02')				THEN 'RIG'
            ELSE LEFT(VIBDBE.SWENR, 5)
    END AS CSHP_CDSHOPPING
FROM `also-analytics-model-nonprod.1_AQUISICAO_S4.vibdbe` AS VIBDBE