CREATE OR REPLACE TABLE FUNCTION `also-analytics-model-nonprod.2_NEGOCIO_S4.TF_UNIDADE_HIST_4B`() AS (
WITH var_contr AS (
  SELECT 
    INTRENO AS INTRENO_VICNCN,
    OBJNR,
    CASE WHEN RECNBEG IS NULL				THEN 2021-01-01
        WHEN RECNBEG = ''				THEN 2021-01-01
        WHEN RECNBEG <	2021-01-01	THEN 2021-01-01
        ELSE RECNBEG
    END AS RECNBEG,
    CASE WHEN RECNENDABS IS NULL			THEN 2031-01-01
        WHEN RECNENDABS = '' 			THEN 2031-01-01
        WHEN RECNENDABS > 2031-01-01	THEN 2031-01-01
        ELSE RECNENDABS
    END AS RECNENDABS
  FROM `also-analytics-model-nonprod.1_AQUISICAO_S4.vicncn`
),
    
var_contr_tempo AS (
		SELECT 
			CONTR.INTRENO_VICNCN,
			CONTR.OBJNR,
			TEMPO.CALMONTH,
			CONTR.RECNBEG,
			CONTR.RECNENDABS
		FROM  var_contr AS CONTR
		INNER JOIN `also-analytics-model-nonprod.1_AQUISICAO_MXM.dim_tempo_mensal` AS TEMPO
	  ON  LEFT(CONTR.RECNBEG, 6) <= TEMPO.CALMONTH
    AND LEFT(CONTR.RECNENDABS, 6) >= TEMPO.CALMONTH 
    WHERE TEMPO.CALMONTH BETWEEN 202101 AND 203101
), 
 
var_vibdobjass AS (
		SELECT
			VIBDOBJASS.MANDT,
			VIBDOBJASS.OBJNRSRC,
			VIBDOBJASS.OBJASSTYPE,
			VIBDOBJASS.OBJNRTRG,
			MAX(VIBDOBJASS.VALIDFROM) AS VALIDFROM,
			TEMPO.CALMONTH
		FROM `also-analytics-model-nonprod.1_AQUISICAO_S4.vibdobjass`   AS VIBDOBJASS
		INNER JOIN `also-analytics-model-nonprod.1_AQUISICAO_MXM.dim_tempo_mensal` AS TEMPO
			ON  CASE WHEN LEFT(VIBDOBJASS.VALIDFROM, 6) = '000000' THEN '202101' ELSE LEFT(VIBDOBJASS.VALIDFROM, 6) END <= TEMPO.CALMONTH
		    AND LEFT(VIBDOBJASS.VALIDTO  , 6) >= TEMPO.CALMONTH
		INNER JOIN `also-analytics-model-nonprod.1_AQUISICAO_S4.vicncn` AS CONTR
			ON CONTR.OBJNR = VIBDOBJASS.OBJNRSRC
		WHERE VIBDOBJASS.OBJASSTYPE = '10'
		  AND TEMPO.CALMONTH BETWEEN '202101' AND '203101'
		GROUP BY 			
			VIBDOBJASS.MANDT,
			VIBDOBJASS.OBJNRSRC,
			VIBDOBJASS.OBJASSTYPE,
			VIBDOBJASS.OBJNRTRG,
			TEMPO.CALMONTH
),
		
  var_vibdobjass_max AS (
		SELECT
			T1.MANDT,
			T1.OBJNRSRC,
			T1.OBJASSTYPE,
			T1.OBJNRTRG,
			T1.VALIDFROM,
			T1.CALMONTH
		FROM var_vibdobjass AS T1
		INNER JOIN 
			(
				SELECT
					MANDT,
					OBJNRSRC,
					OBJASSTYPE,
					MIN(OBJNRTRG) AS OBJNRTRG,
					CALMONTH
				FROM var_vibdobjass
				WHERE OBJASSTYPE = '10'
				GROUP BY
					MANDT,
					OBJNRSRC,
					OBJASSTYPE,
					CALMONTH
			) AS T2
		ON  T1.MANDT      = T2.MANDT
		AND T1.OBJNRSRC   = T2.OBJNRSRC
		AND T1.OBJASSTYPE = T2.OBJASSTYPE
		AND T1.OBJNRTRG   = T2.OBJNRTRG
		AND T1.CALMONTH   = T2.CALMONTH
)
		
		SELECT 
			CONTR.INTRENO_VICNCN			AS INTRENO_VICNCN,
			OBJLOC.INTRENO_VIBDRO			AS INTRENO_VIBDRO,
			CONTR.CALMONTH					AS CALMONTH,
			IFNULL(MEDICAO.FQMFLART, 0)		AS FQMFLART,
			IFNULL(MEDICAO.FQMFLART, 0)		AS FQMFLART_STR,
			IFNULL(MEDICAO.FEINS, 'M2') 	AS FEINS
		FROM var_contr_tempo AS CONTR
		LEFT OUTER JOIN var_vibdobjass_max AS VIBDOBJASS
			ON  CONTR.OBJNR    = VIBDOBJASS.OBJNRSRC
			AND CONTR.CALMONTH = VIBDOBJASS.CALMONTH
		LEFT OUTER JOIN `also-analytics-model-nonprod.3_MATERIALIZADO_S4.DIM_OBJETO_LOCACAO` AS OBJLOC
			ON  VIBDOBJASS.OBJNRTRG = OBJLOC.OBJNR
		LEFT OUTER JOIN `also-analytics-model-nonprod.2_NEGOCIO_S4.TF_OBJETO_LOCACAO_MEDICAO_MENSAL_4B`() AS MEDICAO
			ON  MEDICAO.INTRENO_VIBDRO = OBJLOC.INTRENO_VIBDRO
			AND MEDICAO.CALMONTH       = CONTR.CALMONTH
		WHERE OBJLOC.INTRENO_VIBDRO IS NOT NULL
);