CREATE OR REPLACE TABLE FUNCTION aliansceSonae.2_business.vendas.s4::TF_VENDA_DECLARADA_4B(IP_ATUALIDADE_DADOS STRING(1) DEFAULT 'P' ) 
RETURNS TABLE 
       (
       	CSHP_CDSHOPPING STRING(5),
       	INTRENO_VICNCN STRING (20),
       	INTRENO_ECC STRING (20),
       	CSHP_CDCONTRATO STRING(20),
		CSHP_CDCONTRATO_MXM STRING(20),
		CC_CDCONTRATO STRING (20),
       	RECNNR STRING (13),
       	CALMONTH STRING (6),
       	VALIDFROM DATE,
       	VALIDTO DATE,
       	VERSION STRING (3),
       	TERMNO STRING (4),
		RHYTHMTYPE STRING (4),
		XRHYTHMTYPE STRING(30),
		RPTYPE STRING (4),
		XRPTYPE STRING(30),
		SALESTYPE STRING (4),
		SALESTYPE_TEXT STRING (30),
    	SALESUNIT STRING (3),
    	SALESCURR STRING (5),
    	NO_SALES STRING (1),
    	MAX_VERSION STRING (1),
		RECNTXT STRING (80),
		ZZNMFAN STRING (40),
		XMETXT STRING (60),
		SMENR STRING (8),
		CC_FQMFLART_SONAE DECIMAL (14, 4),
		FQMFLART DECIMAL (14, 4),
	    NET_SALES DECIMAL (15,2),
	    GROSS_SALES DECIMAL (15,2),
	    QUANTITY DECIMAL (17,4),
	    STAT_NETSALES DECIMAL (15,2),
	    STAT_GROSSSALES DECIMAL (15,2),
	    STAT_QUANTITY DECIMAL (17,4)
       )
       

SQL SECURITY DEFINER
  AS 
BEGIN
	var_tivsrrhtt =
		SELECT
			SPRAS,
			RHYTHMTYPE,
			MAX(XRHYTHMTYPE) AS XRHYTHMTYPE
		FROM also-analytics-model-nonprod.1_AQUISICAO_S4.TIVSRRHTT
		WHERE SPRAS = 'P'
		GROUP BY
			SPRAS,
			RHYTHMTYPE;
			
			
			
	var_version =
		SELECT
			MANDT,
			INTRENO,
			TERMNO,
			RHYTHMTYPE,
			VALIDFROM,
			MIN(VERSION) AS VERSION
		FROM also-analytics-model-nonprod.1_AQUISICAO_S4.VISRREPORT
		GROUP BY 
			MANDT,
			INTRENO,
			TERMNO,
			RHYTHMTYPE,
			VALIDFROM;
		
		
  
	
		SELECT
			CONTR.CSHP_CDSHOPPING								AS CSHP_CDSHOPPING,
			VISRREPORT.INTRENO									AS INTRENO_VICNCN,
			CONTR.INTRENO_ECC									AS INTRENO_ECC,
			CONTR.CSHP_CDCONTRATO								AS CSHP_CDCONTRATO,
			CONTR.CSHP_CDCONTRATO_MXM							AS CSHP_CDCONTRATO_MXM,
			CONTR.CC_CDCONTRATO 								AS CC_CDCONTRATO,
			CONTR.RECNNR										AS RECNNR,
			TO_STRING(VISRREPORT.VALIDFROM, 'YYYYMM')			AS CALMONTH,
			VISRREPORT.VALIDFROM								AS VALIDFROM,
			VISRREPORT.VALIDTO									AS VALIDTO,
			VISRREPORT.VERSION									AS VERSION,
			VISRREPORT.TERMNO									AS TERMNO,
			VISRREPORT.RHYTHMTYPE								AS RHYTHMTYPE,
			TIVSRRHTT.XRHYTHMTYPE								AS XRHYTHMTYPE,
			VISRREPORT.RPTYPE									AS RPTYPE,
			TIVSRRPTT.XRPTYPE									AS XRPTYPE,
			VISRREPORT.SALESTYPE								AS SALESTYPE,
		   	CASE VISRREPORT.SALESTYPE
		   		WHEN 'M01'  THEN 'Volume de vendas de cerveja'
		   		WHEN 'S01'  THEN 'Gênero alimentícios'
		   		WHEN 'S02'  THEN 'Vestuário'
		   		WHEN 'S03'  THEN 'Tabaco'
		   		WHEN 'Z001' THEN 'Venda Bomboniere'
		   	    WHEN 'Z002' THEN 'Venda Bilheteria'
		   	    WHEN 'Z003' THEN 'Venda Cigarro'
		   	    WHEN 'Z004' THEN 'Venda Games'
		   	    WHEN 'Z005' THEN 'Venda Papelaria'
		   	    WHEN 'Z006' THEN 'Venda Informática'
		   	    WHEN 'Z007' THEN 'Venda Divulgação'
		   	    WHEN 'Z008' THEN 'Venda Diversas'
		   	    WHEN 'Z009' THEN 'Venda Online'
		   	    WHEN 'Z010' THEN 'Venda Sala Especial'
		   	    WHEN 'Z011' THEN 'Venda Meta'
		   	    WHEN 'Z012' THEN 'Venda Informada'
		   	    ELSE '' 
		   	END 														AS SALESTYPE_TEXT,
			VISRREPORT.SALESUNIT									AS SALESUNIT,
			VISRREPORT.SALESCURR									AS SALESCURR,
			VISRREPORT.NO_SALES										AS NO_SALES,
			CASE WHEN VERSION.INTRENO IS NULL THEN 'N' ELSE 'S' END AS MAX_VERSION,
			CONTR.RECNTXT											AS RECNTXT,
			CONTR.ZZNMFAN											AS ZZNMFAN,
			CONTR.XMETXT											AS XMETXT,
			CONTR.SMENR												AS SMENR,
			CONTR.CC_FQMFLART_SONAE									AS CC_FQMFLART_SONAE,
			CONTR.FQMFLART											AS FQMFLART,
			VISRREPORT.NET_SALES									AS NET_SALES,
			VISRREPORT.GROSS_SALES									AS GROSS_SALES,
			VISRREPORT.QUANTITY										AS QUANTITY,
			VISRREPORT.STAT_NETSALES								AS STAT_NETSALES,
			VISRREPORT.STAT_GROSSSALES								AS STAT_GROSSSALES,
			VISRREPORT.STAT_QUANTITY								AS STAT_QUANTITY
		FROM also-analytics-model-nonprod.1_AQUISICAO_S4.VISRREPORT AS VISRREPORT
	    LEFT OUTER JOIN also-analytics-model-nonprod.DIM_CONTRATO_4P 
	    (placeholder.$$IP_ATUALIDADE_DADOS$$=>:IP_ATUALIDADE_DADOS) AS CONTR
	    	ON VISRREPORT.INTRENO = CONTR.INTRENO_VICNCN
	    LEFT OUTER JOIN :var_tivsrrhtt AS TIVSRRHTT
	    	ON TIVSRRHTT.RHYTHMTYPE = VISRREPORT.RHYTHMTYPE
	    LEFT OUTER JOIN also-analytics-model-nonprod.1_AQUISICAO_S4.TIVSRRPTT AS TIVSRRPTT
	    	ON  TIVSRRPTT.RPTYPE = VISRREPORT.RPTYPE
	    	AND TIVSRRPTT.SPRAS  = 'P'
	    LEFT OUTER JOIN :var_version AS VERSION
	    	ON  VISRREPORT.MANDT      = VERSION.MANDT
			AND VISRREPORT.INTRENO    = VERSION.INTRENO
			AND VISRREPORT.TERMNO     = VERSION.TERMNO
			AND VISRREPORT.RHYTHMTYPE = VERSION.RHYTHMTYPE
			AND VISRREPORT.VALIDFROM  = VERSION.VALIDFROM
			AND VISRREPORT.VERSION	  = VERSION.VERSION;
END;
