CREATE OR REPLACE TABLE FUNCTION `also-analytics-model-nonprod.2_NEGOCIO_S4.TF_VENDA_AUDITADA_4B`() AS (
SELECT
    CONTR.CSHP_CDSHOPPING					            AS CSHP_CDSHOPPING,
    ZTRE016.INTRENO							            AS INTRENO_VICNCN,
    CONTR.CSHP_CDCONTRATO					            AS CSHP_CDCONTRATO,
    CONTR.INTRENO							            AS INTRENO,
    CONTR.INTRENO_ECC						            AS INTRENO_ECC,
    CONTR.CSHP_CDCONTRATO_MXM				            AS CSHP_CDCONTRATO_MXM,
    CONTR.CC_CDCONTRATO 					            AS CC_CDCONTRATO,
    CONTR.BUKRS								            AS BUKRS,
    CONTR.RECNNR							            AS RECNNR,
    FORMAT_DATE('%Y%m', 
                PARSE_DATE('%Y%m%d', ZTRE016.RPDATE))   AS CALMONTH,
    PARSE_DATE('%Y%m%d', ZTRE016.RPDATE)			    AS RPDATE,
    ZTRE016.SALESTYPE						            AS SALESTYPE,
    TIVSRSTT.XSALESTYPE						            AS SALESTYPE_TEXT,
    CONTR.RECNTXT							            AS RECNTXT,
    CONTR.ZZNMFAN							            AS ZZNMFAN,
    CONTR.XMETXT							            AS XMETXT,
    CONTR.SMENR								            AS SMENR,
    CONTR.CDTPAQUISICAO 					            AS CDTPAQUISICAO,
    CONTR.ZZGRPAT_BR						            AS ZZGRPAT_BR,
    CONTR.ZZSUGRP_BR						            AS ZZSUGRP_BR,
    CONTR.ZZATIVM_BR						            AS ZZATIVM_BR,
    CONTR.SNUNR 							            AS SNUNR,
    CONTR.CC_CDGRUPOABL 					            AS CC_CDGRUPOABL,
    CONTR.CDTIPOUNL 						            AS CDTIPOUNL,
    CONTR.KEY_GRPABRASCE					            AS KEY_GRPABRASCE,
    CONTR.KEY_ATVABRASCE					            AS KEY_ATVABRASCE,
    CONTR.CC_FQMFLART_SONAE					            AS CC_FQMFLART_SONAE,
    CONTR.FQMFLART							            AS FQMFLART,
    ZTRE016.GROSS_SALES_AUD_FIS 					    AS GROSS_SALES_AUD_FIS,
    ZTRE016.GROSS_SALES_REDU_Z						    AS GROSS_SALES_REDU_Z,
    ZTRE016.GROSS_SALES_PROJET						    AS GROSS_SALES_PROJET,
    GREATEST(ZTRE016.GROSS_SALES_AUD_FIS, 
            ZTRE016.GROSS_SALES_REDU_Z)				AS VOLVED_AUD
FROM `also-analytics-model-nonprod.1_AQUISICAO_S4.ztre016` AS ZTRE016
    LEFT OUTER JOIN `also-analytics-model-nonprod.3_MATERIALIZADO_S4.DIM_CONTRATO` AS CONTR
    ON ZTRE016.INTRENO = CONTR.INTRENO_VICNCN
LEFT OUTER JOIN `also-analytics-model-nonprod.1_AQUISICAO_S4.tivsrstt` AS TIVSRSTT
    ON  TIVSRSTT.SALESTYPE = ZTRE016.SALESTYPE
    AND TIVSRSTT.SPRAS     = 'P'
);