CREATE TABLE `also-analytics-model-nonprod.3_MATERIALIZADO_S4.DIM_CONDICAO_FAT`
(
  CONDTYPE STRING(4) NOT NULL,
  CONDTYPE_TEXT30 STRING(30),
  ALUG_CONTRATUAL INT64,
  ALUG_FATURADO INT64,
  ALUG_LIQUIDO INT64,
  ALUG_TOT INT64,
  DESC_CARENCIA INT64,
  ALUG_COMPLEMENTAR INT64,
  ENC_COMUM INT64,
  ENC_ESPECIFICO INT64,
  FPP INT64,
  CO INT64,
  CO_COM_ESPECIFICO INT64,
  CARENCIA INT64,
  DESCONTO_PRE INT64,
  NEGATIVO INT64,
  IPTU INT64,
  TX_TRANSF INT64,
  CHANGE_TIME TIMESTAMP
);