CREATE TABLE `also-analytics-model-nonprod.3_MATERIALIZADO_S4.DIM_GRPABRASCE`
(
  KEY_GRPABRASCE STRING(20) NOT NULL,
  SHP_CDSHOPPING STRING(5) NOT NULL,
  ZCODABRASCE INT64,
  GRA_DSGRUPO STRING(40),
  ZGRABRASCE STRING(40),
  CONTADOR INT64,
  CHANGE_TIME TIMESTAMP
);