CREATE TABLE `also-analytics-model-nonprod.3_MATERIALIZADO_S4.DIM_NFANTASIA_HIST`
(
  INTRENO STRING(13) NOT NULL,
  CALMONTH STRING(6) NOT NULL,
  UDATETIME TIMESTAMP,
  ZZNMFAN STRING(40),
  ZZNMFAN_OLD STRING(40),
  ZZNMFAN_NEW STRING(40),
  CONTADOR INT64 NOT NULL,
  CHANGE_TIME TIMESTAMP
);