CREATE TABLE `also-analytics-model-nonprod.3_MATERIALIZADO_S4.DIM_ATVABRASCE`
(
  ATA_CDATIVIDADE STRING(10) NOT NULL,
  ATA_DSATIVIDADE STRING(50),
  ATA_CDGRUPO STRING(10),
  ATA_CDSHOPPING STRING(5),
  CC_CDSHOPPING STRING(5),
  CHANGE_TIME TIMESTAMP
);