CREATE TABLE `also-analytics-model-nonprod.3_MATERIALIZADO_S4.DIM_ALUGMINCONTRATO`
(
  CSHP_CDSHOPPING STRING(5),
  INTRENO_VICNCN STRING(20),
  ROW_NUM INT64,
  CC_VALIDFROM DATE,
  CC_VALIDTO DATE,
  CC_CONDVALUE NUMERIC(15, 2),
  CHANGE_TIME TIMESTAMP
);