CREATE TABLE `also-analytics-model-nonprod.3_MATERIALIZADO_S4.DIM_CLM_DOMINIOS`
(
  CHAVE STRING(50),
  DOMINIO STRING(20),
  TEXTO STRING(100),
  TEXTO_LONGO STRING(100),
  CHANGE_TIME TIMESTAMP
);