CREATE TABLE `also-analytics-model-nonprod.3_MATERIALIZADO_S4.DIM_SHOPPING`
(
  INTRENO_VIBDBE STRING(20) NOT NULL,
  BUKRS STRING(4),
  SWENR_VIBDBE STRING(8),
  XWETEXT STRING(60),
  CSHP_CDSHOPPING STRING(5),
  CHANGE_TIME TIMESTAMP
);