CREATE TABLE `also-analytics-model-nonprod.3_MATERIALIZADO_S4.DIM_UNIDADE_ECONOMICA`
(
  INTRENO_VIBDBE STRING(20) NOT NULL,
  BUKRS STRING(4),
  TXTMD STRING(25),
  SWENR STRING(8),
  OBJNR STRING(22),
  IMKEY STRING(8),
  XWETEXT STRING(60),
  PRCTR STRING(10),
  CSHP_CDSHOPPING STRING(5),
  CHANGE_TIME TIMESTAMP
);