CREATE TABLE `also-analytics-model-nonprod.3_MATERIALIZADO_S4.DIM_UNIDADE_HIST`
(
  INTRENO_VICNCN STRING(20) NOT NULL,
  INTRENO_VIBDRO STRING(20),
  CALMONTH STRING(6) NOT NULL,
  FQMFLART NUMERIC(14, 4),
  FQMFLART_STR STRING(15),
  FEINS STRING(3),
  CHANGE_TIME TIMESTAMP
);