CREATE TABLE `also-analytics-model-nonprod.3_MATERIALIZADO_S4.DIM_CENTRO_LUCRO`
(
  PRCTR STRING(10) NOT NULL,
  BUKRS STRING(4),
  BUKRSF STRING(4),
  SWENR STRING(8),
  CSHP_CDSHOPPING STRING(5),
  INTRENO_VIBDBE STRING(20),
  DATBI STRING(8),
  KOKRS STRING(4),
  KTEXT STRING(20),
  LTEXT STRING(40),
  CHANGE_TIME TIMESTAMP
);