CREATE TABLE `also-analytics-model-nonprod.3_MATERIALIZADO_S4.DIM_EDIFICIO`
(
  BUKRS STRING(4),
  INTRENO_VIBDBU STRING(20) NOT NULL,
  INTRENO_VIBDBE STRING(20),
  SWENR STRING(8),
  SGENR STRING(8),
  OBJNR STRING(22),
  IMKEY STRING(8),
  XGETXT STRING(60),
  RGEBART STRING(2),
  RGEBART_TEXT15 STRING(15),
  RGEBART_TEXT30 STRING(30),
  BANZGE NUMERIC(4, 1),
  AUGESCH NUMERIC(2),
  VALIDFROM DATE,
  VALIDTO DATE,
  GSBER STRING(4),
  PRCTR STRING(10),
  TXJCD STRING(15),
  CSHP_CDSHOPPING STRING(5),
  CHANGE_TIME TIMESTAMP
);