CREATE OR REPLACE TABLE `also-analytics-model-nonprod.3_MATERIALIZADO_S4.VENDA_DIARIA`
(
  CSHP_CDSHOPPING STRING,
  BUKRS STRING,
  INTRENO_VICNCN STRING,
  CSHP_CDCONTRATO STRING,
  INTRENO STRING,
  INTRENO_ECC STRING,
  CSHP_CDCONTRATO_MXM STRING,
  CC_CDCONTRATO STRING,
  CALMONTH STRING,
  RPDATE DATE,
  SALESTYPE STRING,
  FQMFLART NUMERIC,
  CDTPAQUISICAO INT64,
  SMENR STRING,
  XMETXT STRING,
  ZZGRPAT_BR INT64,
  ZZSUGRP_BR INT64,
  ZZATIVM_BR INT64,
  SNUNR STRING,
  CC_CDGRUPOABL STRING,
  CDTIPOUNL STRING,
  KEY_GRPABRASCE STRING,
  KEY_ATVABRASCE STRING,
  ZZNMFAN STRING,
  RECNTXT STRING,
  CC_VOLVED NUMERIC,
  CC_FQMFLART_SONAE NUMERIC,
  CC_VOLVED_COM_FQMFLART NUMERIC,
  CC_FQMFLART_COM_VOLVED NUMERIC,
  GROSS_SALES_AUD_FIS NUMERIC,
  GROSS_SALES_REDU_Z NUMERIC,
  GROSS_SALES_PROJET NUMERIC,
  NET_SALES_INTRAMALL NUMERIC,
  GROSS_SALES_INTRAMALL NUMERIC,
  NET_SALES NUMERIC,
  GROSS_SALES NUMERIC,
  CHANGE_TIME DATETIME
)
PARTITION BY
  DATE_TRUNC(RPDATE, MONTH)
CLUSTER BY
  CSHP_CDSHOPPING
OPTIONS(
  require_partition_filter=true
)