CREATE OR REPLACE TABLE `also-analytics-model-nonprod.3_MATERIALIZADO_S4.VENDA_AUDITADA`
(
  CSHP_CDSHOPPING STRING,
  INTRENO_VICNCN STRING,
  CSHP_CDCONTRATO STRING,
  INTRENO STRING,
  INTRENO_ECC STRING,
  CSHP_CDCONTRATO_MXM STRING,
  CC_CDCONTRATO STRING,
  BUKRS STRING,
  RECNNR STRING,
  CALMONTH STRING,
  RPDATE DATE,
  SALESTYPE STRING,
  SALESTYPE_TEXT STRING,
  RECNTXT STRING,
  ZZNMFAN STRING,
  XMETXT STRING,
  SMENR STRING,
  CDTPAQUISICAO INT64,
  ZZGRPAT_BR INT64,
  ZZSUGRP_BR INT64,
  ZZATIVM_BR INT64,
  SNUNR STRING,
  CC_CDGRUPOABL STRING,
  CDTIPOUNL STRING,
  KEY_GRPABRASCE STRING,
  KEY_ATVABRASCE STRING,
  CC_FQMFLART_SONAE NUMERIC,
  FQMFLART NUMERIC,
  GROSS_SALES_AUD_FIS NUMERIC,
  GROSS_SALES_REDU_Z NUMERIC,
  GROSS_SALES_PROJET NUMERIC,
  VOLVED_AUD NUMERIC
)
PARTITION BY
  DATE_TRUNC(RPDATE, MONTH)
CLUSTER BY
  CSHP_CDSHOPPING