CREATE OR REPLACE PROCEDURE `also-analytics-model-nonprod.3_MATERIALIZADO_S4.DIM_UNIDADE_ECONOMICA` () 
	
BEGIN
		DELETE FROM `also-analytics-model-nonprod.3_MATERIALIZADO_S4.DIM_UNIDADE_ECONOMICA` WHERE 1=1;

    CREATE OR REPLACE TABLE `also-analytics-model-nonprod.3_MATERIALIZADO_S4.DIM_UNIDADE_ECONOMICA`
    AS
    SELECT
		INTRENO_VIBDBE, BUKRS, TXTMD, SWENR, OBJNR, IMKEY, XWETEXT, PRCTR, CSHP_CDSHOPPING, CURRENT_TIMESTAMP() AS CHANGE_TIME
		FROM `also-analytics-model-nonprod.2_NEGOCIO_S4.TF_UNIDADE_ECONOMICA_4B`();

		-- INSERT INTO `also-analytics-model-nonprod.3_MATERIALIZADO_S4.DIM_UNIDADE_ECONOMICA`
		-- (INTRENO_VIBDBE, BUKRS, TXTMD, SWENR, OBJNR, IMKEY, XWETEXT, PRCTR, CSHP_CDSHOPPING, CHANGE_TIME)
		-- SELECT
		-- INTRENO_VIBDBE, BUKRS, TXTMD, SWENR, OBJNR, IMKEY, XWETEXT, PRCTR, CSHP_CDSHOPPING, CURRENT_TIMESTAMP() AS CHANGE_TIME
		-- FROM `also-analytics-model-nonprod.2_NEGOCIO_S4.TF_UNIDADE_ECONOMICA_4B`();
END;
