CREATE OR REPLACE TABLE PROCEDURE `also-analytics-model-prod.3_MATERIALIZADO_S4.DIM_EDIFICIO` () 

BEGIN
		DELETE FROM `also-analytics-model-prod.3_MATERIALIZADO_S4.DIM_EDIFICIO` WHERE 1=1;


		INSERT INTO `also-analytics-model-prod.3_MATERIALIZADO_S4.DIM_EDIFICIO`
		(INTRENO_VIBDBU,BUKRS,SWENR,SGENR,XGETXT,RGEBART,RGEBART_TEXT15,RGEBART_TEXT30,BANZGE,AUGESCH,OBJNR,IMKEY,TXJCD,PRCTR,GSBER,
		 INTRENO_VIBDBE,CSHP_CDSHOPPING,VALIDFROM,VALIDTO,CHANGE_TIME)
		SELECT
		 INTRENO_VIBDBU,BUKRS,SWENR,SGENR,XGETXT,RGEBART,RGEBART_TEXT15,RGEBART_TEXT30,BANZGE,AUGESCH,OBJNR,IMKEY,TXJCD,PRCTR,GSBER,
		 INTRENO_VIBDBE,CSHP_CDSHOPPING,VALIDFROM,VALIDTO,CURRENT_TIMESTAMP() AS CHANGE_TIME
		FROM `also-analytics-model-prod.2_NEGOCIO_S4.TF_EDIFICIO_4B`();
			 
END;
