CREATE OR REPLACE TABLE PROCEDURE `also-analytics-model-prod.3_MATERIALIZADO_S4.DIM_DEDUCAOMINALUG` () 
	
BEGIN
		DELETE FROM `also-analytics-model-prod.3_MATERIALIZADO_S4.DIM_DEDUCAOMINALUG` WHERE 1=1;


		INSERT INTO `also-analytics-model-prod.3_MATERIALIZADO_S4.DIM_DEDUCAOMINALUG`
		(INTRENO_VICNCN, CSHP_CDSHOPPING, CC_CDCONTRATO, RECNNR, BUKRS, FLOWTYPE, DTINI, DTFIM, ZFAEL, ZPRZ1,
		 ZZLSPR, ZPONTEQ, ZOBS, DMBTR, CPUDT, CPUTM, USNAM, UPDDT, USNAU, CC_TPVALOR, CC_VLREDUCAO, CHANGE_TIME)
		SELECT
		 INTRENO_VICNCN, CSHP_CDSHOPPING, CC_CDCONTRATO, RECNNR, BUKRS, FLOWTYPE, DTINI, DTFIM, ZFAEL, ZPRZ1,
		 ZZLSPR, ZPONTEQ, ZOBS, DMBTR, CPUDT, CPUTM, USNAM, UPDDT, USNAU, CC_TPVALOR, CC_VLREDUCAO, CURRENT_TIMESTAMP() AS CHANGE_TIME
		FROM `also-analytics-model-prod.2_NEGOCIO_S4.TF_DEDUCAOMINALUG_4B` ();
		
END;
