CREATE OR REPLACE PROCEDURE `also-analytics-model-nonprod.3_MATERIALIZADO_S4.DIM_GRPABL` () 
BEGIN
		DELETE FROM `also-analytics-model-nonprod.3_MATERIALIZADO_S4.DIM_GRPABL` WHERE 1=1;

    CREATE OR REPLACE TABLE `also-analytics-model-nonprod.3_MATERIALIZADO_S4.DIM_GRPABL`
    AS
    SELECT
		 ZCODABL, ZGRABL, CDGRPABL, DSGRPABL, CURRENT_TIMESTAMP() AS CHANGE_TIME
		FROM `also-analytics-model-nonprod.2_NEGOCIO_S4.TF_GRPABL_4B`();


		-- INSERT INTO `also-analytics-model-nonprod.3_MATERIALIZADO_S4.DIM_GRPABL`
		-- (ZCODABL, ZGRABL, CDGRPABL, DSGRPABL, CHANGE_TIME)
		-- SELECT
		--  ZCODABL, ZGRABL, CDGRPABL, DSGRPABL, CURRENT_TIMESTAMP() AS CHANGE_TIME
		-- FROM `also-analytics-model-nonprod.2_NEGOCIO_S4.TF_GRPABL_4B`();

END;
