CREATE OR REPLACE TABLE PROCEDURE `also-analytics-model-prod.3_MATERIALIZADO_S4.DIM_GRPABRASCE` () 

BEGIN
		DELETE FROM `also-analytics-model-prod.3_MATERIALIZADO_S4.DIM_GRPABRASCE` WHERE 1=1;

		INSERT INTO `also-analytics-model-prod.3_MATERIALIZADO_S4.DIM_GRPABRASCE`
		(SHP_CDSHOPPING,KEY_GRPABRASCE,GRA_DSGRUPO,ZCODABRASCE,ZGRABRASCE,CONTADOR,CHANGE_TIME)
		SELECT
			SHP_CDSHOPPING,KEY_GRPABRASCE,GRA_DSGRUPO,ZCODABRASCE,ZGRABRASCE,CONTADOR,CURRENT_TIMESTAMP() AS CHANGE_TIME
		FROM `also-analytics-model-prod.2_NEGOCIO_S4.TF_GRPABRASCE_4B`();
			
END;
