CREATE OR REPLACE PROCEDURE `also-analytics-model-nonprod.3_MATERIALIZADO_S4.DIM_EDIFICIO` () 
OPTIONS(strict_mode=false)
BEGIN
		--DELETE FROM `also-analytics-model-nonprod.3_MATERIALIZADO_S4.DIM_EDIFICIO` WHERE 1=1;

    CREATE OR REPLACE TABLE `also-analytics-model-nonprod.3_MATERIALIZADO_S4.DIM_EDIFICIO`
    AS
		SELECT
		 INTRENO_VIBDBU,BUKRS,SWENR,SGENR,XGETXT,RGEBART,RGEBART_TEXT15,RGEBART_TEXT30,BANZGE,AUGESCH,OBJNR,IMKEY,TXJCD,PRCTR,GSBER,
		 INTRENO_VIBDBE,CSHP_CDSHOPPING,VALIDFROM,VALIDTO,CURRENT_TIMESTAMP() AS CHANGE_TIME
		FROM `also-analytics-model-nonprod.2_NEGOCIO_S4.TF_EDIFICIO_4B`();
			 
END;
