CREATE OR REPLACE TABLE PROCEDURE `also-analytics-model-prod.3_MATERIALIZADO_S4.DIM_UNIDADE_ECONOMICA` () 
	
BEGIN
		DELETE FROM `also-analytics-model-prod.3_MATERIALIZADO_S4.DIM_UNIDADE_ECONOMICA` WHERE 1=1;

		INSERT INTO `also-analytics-model-prod.3_MATERIALIZADO_S4.DIM_UNIDADE_ECONOMICA`
		(INTRENO_VIBDBE, BUKRS, TXTMD, SWENR, OBJNR, IMKEY, XWETEXT, PRCTR, CSHP_CDSHOPPING, CHANGE_TIME)
		SELECT
		INTRENO_VIBDBE, BUKRS, TXTMD, SWENR, OBJNR, IMKEY, XWETEXT, PRCTR, CSHP_CDSHOPPING, CURRENT_TIMESTAMP() AS CHANGE_TIME
		FROM `also-analytics-model-prod.2_NEGOCIO_S4.TF_UNIDADE_ECONOMICA_4B`();
END;
