CREATE OR REPLACE TABLE PROCEDURE `also-analytics-model-prod.3_MATERIALIZADO_S4.DIM_EMPRESA` () 

BEGIN
		DELETE FROM `also-analytics-model-prod.3_MATERIALIZADO_S4.DIM_EMPRESA` WHERE 1=1;

		INSERT INTO `also-analytics-model-prod.3_MATERIALIZADO_S4.DIM_EMPRESA`
		(BUKRS,BUTXT,ORT01,CSHP_CDSHOPPING,CHANGE_TIME)
		SELECT
		 BUKRS,BUTXT,ORT01,CSHP_CDSHOPPING,CURRENT_TIMESTAMP() AS CHANGE_TIME
		FROM `also-analytics-model-prod.2_NEGOCIO_S4.TF_EMPRESA_4B` ();	
END;
