CREATE OR REPLACE TABLE PROCEDURE `also-analytics-model-prod.3_MATERIALIZADO_S4.DIM_ACRESCIMOCONTRATO` () 

BEGIN
		DELETE FROM `also-analytics-model-prod.3_MATERIALIZADO_S4.DIM_ACRESCIMOCONTRATO` WHERE 1=1;


		INSERT INTO `also-analytics-model-prod.3_MATERIALIZADO_S4.DIM_ACRESCIMOCONTRATO`
		(CSHP_CDSHOPPING, INTRENO_VICNCN, ROW_NUM, NUMESES, CC_VALIDFROM, CC_VALIDTO, CC_CONDVALUE, CC_CONDPERC, CHANGE_TIME)
		SELECT
		 CSHP_CDSHOPPING, INTRENO_VICNCN, ROW_NUM, NUMESES, CC_VALIDFROM, CC_VALIDTO, CC_CONDVALUE, CC_CONDPERC, CURRENT_TIMESTAMP() AS CHANGE_TIME
		FROM `also-analytics-model-prod.2_NEGOCIO_S4.TF_ACRESCIMOCONTRATO_4B`();
			
END;
