CREATE OR REPLACE PROCEDURE `also-analytics-model-nonprod.3_MATERIALIZADO_S4.DIM_SHOPPING` () 
	
BEGIN
		--DELETE FROM `also-analytics-model-nonprod.3_MATERIALIZADO_S4.DIM_SHOPPING` WHERE 1=1;

		CREATE OR REPLACE `also-analytics-model-nonprod.3_MATERIALIZADO_S4.DIM_SHOPPING`
		AS
		SELECT
			INTRENO_VIBDBE,CSHP_CDSHOPPING,XWETEXT,SWENR_VIBDBE,BUKRS,CURRENT_TIMESTAMP() AS CHANGE_TIME
		FROM `also-analytics-model-nonprod.2_NEGOCIO_S4.TF_SHOPPING_4B` ();
	
END;