CREATE OR REPLACE TABLE PROCEDURE `also-analytics-model-prod.3_MATERIALIZADO_S4.DIM_CENTRO_LUCRO` () 
	
BEGIN
		DELETE FROM `also-analytics-model-prod.3_MATERIALIZADO_S4.DIM_CENTRO_LUCRO` WHERE 1=1;

		INSERT INTO `also-analytics-model-prod.3_MATERIALIZADO_S4.DIM_CENTRO_LUCRO`
		(PRCTR,BUKRS,BUKRSF,SWENR,CSHP_CDSHOPPING,INTRENO_VIBDBE,DATBI,KOKRS,KTEXT,LTEXT,CHANGE_TIME)
		SELECT
		 PRCTR,BUKRS,BUKRSF,SWENR,CSHP_CDSHOPPING,INTRENO_VIBDBE,DATBI,KOKRS,KTEXT,LTEXT,CURRENT_TIMESTAMP() AS CHANGE_TIME
		FROM `also-analytics-model-prod.2_NEGOCIO_S4.TF_CENTRO_LUCRO_4B`();
END;
