CREATE OR REPLACE PROCEDURE `also-analytics-model-nonprod.3_MATERIALIZADO_S4.DIM_ATVABRASCE` () 

BEGIN
		DELETE FROM `also-analytics-model-nonprod.3_MATERIALIZADO_S4.DIM_ATVABRASCE` WHERE 1=1;

    CREATE OR REPLACE TABLE `also-analytics-model-nonprod.3_MATERIALIZADO_S4.DIM_ATVABRASCE`
    AS
    SELECT
		 ATA_CDATIVIDADE, ATA_DSATIVIDADE, ATA_CDGRUPO, ATA_CDSHOPPING, CC_CDSHOPPING, CURRENT_TIMESTAMP() AS CHANGE_TIME
		FROM `also-analytics-model-nonprod.2_NEGOCIO_S4.TF_ATVABRASCE_4B`();

		-- INSERT INTO `also-analytics-model-nonprod.3_MATERIALIZADO_S4.DIM_ATVABRASCE`
		-- (ATA_CDATIVIDADE, ATA_DSATIVIDADE, ATA_CDGRUPO, ATA_CDSHOPPING, CC_CDSHOPPING, CHANGE_TIME)
		-- SELECT
		--  ATA_CDATIVIDADE, ATA_DSATIVIDADE, ATA_CDGRUPO, ATA_CDSHOPPING, CC_CDSHOPPING, CURRENT_TIMESTAMP() AS CHANGE_TIME
		-- FROM `also-analytics-model-nonprod.2_NEGOCIO_S4.TF_ATVABRASCE_4B`();

END;