CREATE OR REPLACE TABLE PROCEDURE also-analytics-model-prod.3_MATERIALIZADO_S4.DIM_CONDESPEC_CES_4M () 
	
	 
	
	AS
BEGIN
		DELETE FROM also-analytics-model-prod.1_AQUISICAO_S4.DIM_CONDESPEC_CES WHERE 1=1;


		INSERT INTO also-analytics-model-prod.1_AQUISICAO_S4.DIM_CONDESPEC_CES
		(CSHP_CDSHOPPING, INTRENO_VICNCN, BUKRS, RECNNR, CES_CDSHOPPING, CES_CDCONTRATO, CES_CDCONTA, CES_VLCONDICAO, CES_DDVENCIMENTO, 
		 CES_DDREAJUSTE, CES_DTBASEREAJUSTE, CES_DDPROGRECEB, MOE_DESCRICAO, CCO_NMCONTA, CC_TPCONDICAO, CC_TPCALCULO, CC_CORRECOES, 
		 CC_DIFPAGAEMP, CC_RERATEIO, CC_TIPOBASE, CC_DIAUTIL, CC_MESINICIO, CC_MESFIM, CC_NAOPARTICRATEIO, CHANGE_TIME)
		SELECT
		 CSHP_CDSHOPPING, INTRENO_VICNCN, BUKRS, RECNNR, CES_CDSHOPPING, CES_CDCONTRATO, CES_CDCONTA, CES_VLCONDICAO, CES_DDVENCIMENTO, 
		 CES_DDREAJUSTE, CES_DTBASEREAJUSTE, CES_DDPROGRECEB, MOE_DESCRICAO, CCO_NMCONTA, CC_TPCONDICAO, CC_TPCALCULO, CC_CORRECOES, 
		 CC_DIFPAGAEMP, CC_RERATEIO, CC_TIPOBASE, CC_DIAUTIL, CC_MESINICIO, CC_MESFIM, CC_NAOPARTICRATEIO, CURRENT_TIMESTAMP() AS CHANGE_TIME
		FROM also-analytics-model-prod.2_NEGOCIO_S4.TF_CONDESPEC_CES_4B
			(placeholder.$$IP_ATUALIDADE_DADOS$$=>'P');
			
			
		
END;
