CREATE OR REPLACE TABLE PROCEDURE also-analytics-model-prod.3_MATERIALIZADO_S4.DIM_CONDICAO_4M () 
	
	 
	
	AS
BEGIN
		DELETE FROM also-analytics-model-prod.1_AQUISICAO_S4.DIM_CONDICAO WHERE 1=1;


		INSERT INTO also-analytics-model-prod.1_AQUISICAO_S4.DIM_CONDICAO
		(CONDTYPE,CONDTYPE_TEXT20,CONDTYPE_TEXT30,CONDPROP,CONDPROP_TEXT,FLOWTYPE,FLOWTYPE_TEXT,CALCRULEEXT,CALCRULEEXT_TEXT15,CALCRULEEXT_TEXT30,CALCRULEEXT_TEXT60,
		 DISTRULEEXT,DISTRULEEXT_TEXT_15,DISTRULEEXT_TEXT_30,DISTRULEEXT_TEXT_60,SSOLHAB,SSOLHAB_TEXT,UNITPRICE,CHANGE_TIME)
		SELECT
		 CONDTYPE,CONDTYPE_TEXT20,CONDTYPE_TEXT30,CONDPROP,CONDPROP_TEXT,FLOWTYPE,FLOWTYPE_TEXT,CALCRULEEXT,CALCRULEEXT_TEXT15,CALCRULEEXT_TEXT30,CALCRULEEXT_TEXT60,
		 DISTRULEEXT,DISTRULEEXT_TEXT_15,DISTRULEEXT_TEXT_30,DISTRULEEXT_TEXT_60,SSOLHAB,SSOLHAB_TEXT,UNITPRICE,CURRENT_TIMESTAMP() AS CHANGE_TIME
		FROM also-analytics-model-prod.2_NEGOCIO_S4.TF_CONDICAO_4B;
		
		
		
END;
