CREATE OR REPLACE PROCEDURE `also-analytics-model-nonprod.3_MATERIALIZADO_S4.DIM_EMPRESA` () 
OPTIONS(strict_mode=false)
BEGIN
		DELETE FROM `also-analytics-model-nonprod.3_MATERIALIZADO_S4.DIM_EMPRESA` WHERE 1=1;

		INSERT INTO `also-analytics-model-nonprod.3_MATERIALIZADO_S4.DIM_EMPRESA`
		(BUKRS,BUTXT,ORT01,CSHP_CDSHOPPING,CHANGE_TIME)
		SELECT
		 BUKRS,BUTXT,ORT01,CSHP_CDSHOPPING,CURRENT_TIMESTAMP() AS CHANGE_TIME
		FROM `also-analytics-model-nonprod.2_NEGOCIO_S4.TF_EMPRESA_4B` ();	
END;
