CREATE OR REPLACE TABLE PROCEDURE also-analytics-model-prod.3_MATERIALIZADO_S4.DIM_CLM_DOMINIOS_4M () 
	
	 
	---
	AS
BEGIN
		DELETE FROM also-analytics-model-prod.1_AQUISICAO_S4.DIM_CLM_DOMINIOS WHERE 1=1;

		INSERT INTO also-analytics-model-prod.1_AQUISICAO_S4.DIM_CLM_DOMINIOS
		(CHAVE,DOMINIO,TEXTO,CHANGE_TIME,TEXTO_LONGO)
		SELECT
		CHAVE,DOMINIO,TEXTO,CURRENT_TIMESTAMP() AS CHANGE_TIME,TEXTO_LONGO
		FROM also-analytics-model-prod.2_NEGOCIO_S4.TF_CLM_DOMINIOS_4B;
		
		
		DELETE from also-analytics-model-prod.1_AQUISICAO_S4.HIER_CLM WHERE NIVEL_1 LIKE '%APL%' AND CONTA != '-250';
		
		
		INSERT INTO also-analytics-model-prod.1_AQUISICAO_S4.HIER_CLM (
		SELECT 'APLICAÇÃO',TEXTO, NULL, NULL, NULL, NULL, CHAVE
		FROM also-analytics-model-prod.2_NEGOCIO_S4.TF_CLM_DOMINIOS_4B
		WHERE DOMINIO = 'CONTA_BANCARIA');

		INSERT INTO also-analytics-model-prod.1_AQUISICAO_S4.HIER_CLM (
		SELECT 'APLICAÇÃO MENSAL',TEXTO, NULL, NULL, NULL, NULL, CHAVE||'01' AS CHAVE
		FROM also-analytics-model-prod.2_NEGOCIO_S4.TF_CLM_DOMINIOS_4B
		WHERE DOMINIO = 'CONTA_BANCARIA');	
		
		INSERT INTO also-analytics-model-prod.1_AQUISICAO_S4.HIER_CLM (
		SELECT 'APLICAÇÃO QUINZENAL',TEXTO, NULL, NULL, NULL, NULL, CHAVE||'02' AS CHAVE
		FROM also-analytics-model-prod.2_NEGOCIO_S4.TF_CLM_DOMINIOS_4B
		WHERE DOMINIO = 'CONTA_BANCARIA');
		
		
END;