CREATE OR REPLACE PROCEDURE `also-analytics-model-nonprod.3_MATERIALIZADO_S4.DIM_UNIDADE_HIST`()
OPTIONS (strict_mode=false)
BEGIN
		DELETE FROM `also-analytics-model-nonprod.3_MATERIALIZADO_S4.DIM_UNIDADE_HIST` WHERE 1=1;

		CREATE OR REPLACE TABLE `also-analytics-model-nonprod.3_MATERIALIZADO_S4.DIM_UNIDADE_HIST`
		AS
		SELECT *,CURRENT_TIMESTAMP() AS CHANGE_TIME FROM `also-analytics-model-nonprod.2_NEGOCIO_S4.TF_UNIDADE_HIST_4B` ();

		-- INSERT INTO `also-analytics-model-nonprod.3_MATERIALIZADO_S4.DIM_UNIDADE_HIST`
		-- (INTRENO_VICNCN,INTRENO_VIBDRO,CALMONTH,FQMFLART,FQMFLART_STR,FEINS,CHANGE_TIME)
		-- SELECT
		-- INTRENO_VICNCN,INTRENO_VIBDRO,CALMONTH,FQMFLART,FQMFLART_STR,FEINS,CURRENT_TIMESTAMP() AS CHANGE_TIME
		-- FROM `also-analytics-model-nonprod.2_NEGOCIO_S4.TF_UNIDADE_HIST_4B` ();

END;