CREATE OR REPLACE TABLE PROCEDURE `also-analytics-model-prod.3_MATERIALIZADO_S4.DIM_SHOPPING` () 
	
BEGIN
		DELETE FROM `also-analytics-model-prod.3_MATERIALIZADO_S4.DIM_SHOPPING` WHERE 1=1;

		INSERT INTO `also-analytics-model-prod.3_MATERIALIZADO_S4.DIM_SHOPPING`
		(INTRENO_VIBDBE,CSHP_CDSHOPPING,XWETEXT,SWENR_VIBDBE,BUKRS,CHANGE_TIME)
		SELECT
			INTRENO_VIBDBE,CSHP_CDSHOPPING,XWETEXT,SWENR_VIBDBE,BUKRS,CURRENT_TIMESTAMP() AS CHANGE_TIME
		FROM `also-analytics-model-prod.2_NEGOCIO_S4.TF_SHOPPING_4B` ();
	
END;