CREATE OR REPLACE TABLE PROCEDURE also-analytics-model-prod.3_MATERIALIZADO_S4.DIM_CONDICAO_FAT_4M () 
	
	 
	
	AS
BEGIN
		DELETE FROM also-analytics-model-prod.1_AQUISICAO_S4.DIM_CONDICAO_FAT WHERE 1=1;


		INSERT INTO also-analytics-model-prod.1_AQUISICAO_S4.DIM_CONDICAO_FAT
		(CONDTYPE, CONDTYPE_TEXT30, ENC_ESPECIFICO, DESC_CARENCIA, ALUG_LIQUIDO, ENC_COMUM, ALUG_TOT, DESCONTO_PRE, 
		 ALUG_FATURADO, ALUG_COMPLEMENTAR, CARENCIA, ALUG_CONTRATUAL, CO_COM_ESPECIFICO, CO, TX_TRANSF, FPP, IPTU, 
		 NEGATIVO, CHANGE_TIME)
		SELECT
		 CONDTYPE, CONDTYPE_TEXT30, ENC_ESPECIFICO, DESC_CARENCIA, ALUG_LIQUIDO, ENC_COMUM, ALUG_TOT, DESCONTO_PRE, 
		  ALUG_FATURADO, ALUG_COMPLEMENTAR, CARENCIA, ALUG_CONTRATUAL, CO_COM_ESPECIFICO, CO, TX_TRANSF, FPP, IPTU, 
		  NEGATIVO, CURRENT_TIMESTAMP() AS CHANGE_TIME
		FROM also-analytics-model-prod.2_NEGOCIO_S4.TF_CONDICAO_FAT_4B
		     (placeholder.$$IP_ATUALIDADE_DADOS$$=>'P');
		
		
		
END;
