CREATE OR REPLACE TABLE PROCEDURE also-analytics-model-prod.3_MATERIALIZADO_S4.DIM_CONTRATO_HIST_4M (IN var_calmonth TABLE(CALMONTH STRING(6))) 

BEGIN
	DECLARE VAR_I INT;
	DECLARE VAR_COUNT INT;
	DECLARE VAR_CURRENT STRING(6);
	
	
	SELECT COUNT(*)
	INTO VAR_COUNT
	FROM :var_calmonth;
	
	FOR VAR_I IN 0 .. :VAR_COUNT-1 DO
	    SELECT CALMONTH
	    INTO VAR_CURRENT
	    FROM :var_calmonth
	    LIMIT 1 OFFSET :VAR_I;
	    SELECT :VAR_CURRENT FROM DUMMY;
	    
	    DELETE FROM also-analytics-model-prod.1_AQUISICAO_S4.DIM_CONTRATO_HIST
		WHERE CALMONTH = :VAR_CURRENT;


		INSERT INTO also-analytics-model-prod.1_AQUISICAO_S4.DIM_CONTRATO_HIST
		(CALMONTH, INTRENO_VICNCN, INTRENO_VIBDRO, INTRENO_VIBDBU, BUKRS, RECNNR, OBJNR, IMKEY, RECNTYPE, RECNTYPE_TEXT15, RECNTYPE_TEXT30, RECNBEG, 
		 RECNENDABS, RECNTXT, RECNDACTIV, RECNTXTOLD, RECNBUKRSCOLLECT, RECNNRCOLLECT, RECNDAT, RECNEND1ST, RECNNOTPER, RECNNOTRECEIPT, 
		 RECNNOTREASON, RECNNOTREASON_TEXT15, RECNNOTREASON_TEXT30, RECNDAKTKU, BENOCN, TRANSPOSSFROM, TRANSPOSSTO, ZZLJRISCO, ZZBRINCEND, 
		 ZCODABL, ZZCLASS_ZGRABL, ZCODABRASCE, ZZCLASS_ZGRABRASCE, ZCODREDE, ZZCLASS_ZREDE, ZCODGAR, ZZCLASS_ZTPGARANTIA, CODNATPB, ZZCLASS_ZNATPB, 
		 ZZINTEREST_PERCENT, ZZFINE_PERCENT, ZZMONETARY_INDEX, ZZINDEX_YEAR, ZZRECSF, ZZREDILJ, ZZRECONS, ZZRECOB, ZZRENED, ZZRECES, ZZREIREF, 
		 ZZREFREF, ZZREPREF, XMETXT, FQMFLART, FEINS, CDTPAQUISICAO, CSHP_CDSHOPPING, CSHP_CDCONTRATO, CSHP_NMFANTASIA, CSHP_DTCADASTRO, CSHP_DTINICIO, 
		 CSHP_DTFIM, CSHP_DTENCERRAMENTO, CSHP_DDREAJUSTE, CSHP_DTBASEREAJUSTE, CSHP_PCMULTA, CSHP_PCJUROS, CSHP_DTINAUGURA, CSHP_PRAZO, CSHP_DTASSINATURA, 
		 CSHP_CDSTATUS, CSHP_IDREDELOJA, RLS_NOMEREDE, CSHP_DTINCLUSAO, CSHP_DTDISTRATO, CC_CDGRUPO, CC_ABL, CSHP_CDATIVIDADE, CSHP_VBPOSSUIACRESESP, 
		 CC_CDGRUPOABL, CSHP_CDTIPOUNL, INTRENO, DMIBEG, DMIEND, ZZNMFAN, SMENR, ZZGRPAT_BR, ZZSUGRP_BR, ZZATIVM_BR, SNUNR, DKUEZU, DAKTV, USR08, 
		 SMIVE, CDTIPOUNL, ABNNR, KEY_GRPABRASCE, KEY_ATVABRASCE, CC_FQMFLART_SONAE, INTRENO_ECC, CSHP_CDCONTRATO_MXM, CC_CDCONTRATO, SWENR, 
		 INTRENO_VIBDBE, PARTNER_TR0200, PARTNER_TR0600, PARTNER_TR0605, PARTNER_TR0806, CC_DIAS_VENCTO, FLAG_ATIVO, PARTNER_TR0200_NAME, PARTNER_TR0600_NAME, 
		 PARTNER_TR0605_NAME, PARTNER_TR0806_NAME, FLAG_CTO, CC_SMIVE, ADJMFIRSTDATE, CC_PERIO_REAJUSTE, CDUNIDADE, ZZREDFIM, CHANGE_TIME)
		SELECT
		 CALMONTH, INTRENO_VICNCN, INTRENO_VIBDRO, INTRENO_VIBDBU, BUKRS, RECNNR, OBJNR, IMKEY, RECNTYPE, RECNTYPE_TEXT15, RECNTYPE_TEXT30, RECNBEG, 
		 RECNENDABS, RECNTXT, RECNDACTIV, RECNTXTOLD, RECNBUKRSCOLLECT, RECNNRCOLLECT, RECNDAT, RECNEND1ST, RECNNOTPER, RECNNOTRECEIPT, 
		 RECNNOTREASON, RECNNOTREASON_TEXT15, RECNNOTREASON_TEXT30, RECNDAKTKU, BENOCN, TRANSPOSSFROM, TRANSPOSSTO, ZZLJRISCO, ZZBRINCEND, 
		 ZCODABL, ZZCLASS_ZGRABL, ZCODABRASCE, ZZCLASS_ZGRABRASCE, ZCODREDE, ZZCLASS_ZREDE, ZCODGAR, ZZCLASS_ZTPGARANTIA, CODNATPB, ZZCLASS_ZNATPB, 
		 ZZINTEREST_PERCENT, ZZFINE_PERCENT, ZZMONETARY_INDEX, ZZINDEX_YEAR, ZZRECSF, ZZREDILJ, ZZRECONS, ZZRECOB, ZZRENED, ZZRECES, ZZREIREF, 
		 ZZREFREF, ZZREPREF, XMETXT, FQMFLART, FEINS, CDTPAQUISICAO, CSHP_CDSHOPPING, CSHP_CDCONTRATO, CSHP_NMFANTASIA, CSHP_DTCADASTRO, CSHP_DTINICIO, 
		 CSHP_DTFIM, CSHP_DTENCERRAMENTO, CSHP_DDREAJUSTE, CSHP_DTBASEREAJUSTE, CSHP_PCMULTA, CSHP_PCJUROS, CSHP_DTINAUGURA, CSHP_PRAZO, CSHP_DTASSINATURA, 
		 CSHP_CDSTATUS, CSHP_IDREDELOJA, RLS_NOMEREDE, CSHP_DTINCLUSAO, CSHP_DTDISTRATO, CC_CDGRUPO, CC_ABL, CSHP_CDATIVIDADE, CSHP_VBPOSSUIACRESESP, 
		 CC_CDGRUPOABL, CSHP_CDTIPOUNL, INTRENO, DMIBEG, DMIEND, ZZNMFAN, SMENR, ZZGRPAT_BR, ZZSUGRP_BR, ZZATIVM_BR, SNUNR, DKUEZU, DAKTV, USR08, 
		 SMIVE, CDTIPOUNL, ABNNR, KEY_GRPABRASCE, KEY_ATVABRASCE, CC_FQMFLART_SONAE, INTRENO_ECC, CSHP_CDCONTRATO_MXM, CC_CDCONTRATO, SWENR,
		 INTRENO_VIBDBE, PARTNER_TR0200, PARTNER_TR0600, PARTNER_TR0605, PARTNER_TR0806, CC_DIAS_VENCTO, FLAG_ATIVO, PARTNER_TR0200_NAME, PARTNER_TR0600_NAME, 
		 PARTNER_TR0605_NAME, PARTNER_TR0806_NAME, FLAG_CTO, CC_SMIVE, ADJMFIRSTDATE, CC_PERIO_REAJUSTE, CDUNIDADE, ZZREDFIM, CURRENT_TIMESTAMP() AS CHANGE_TIME
		FROM also-analytics-model-prod.2_NEGOCIO_S4.TF_CONTRATO_HIST_4B
			 (placeholder.$$IP_ATUALIDADE_DADOS$$=>'P',
			  placeholder.$$IP_COMPETEC$$=>:VAR_CURRENT)
		WHERE CALMONTH = :VAR_CURRENT;
	END FOR;
	
	
	
END;
