CREATE OR REPLACE PROCEDURE `also-analytics-model-nonprod.3_MATERIALIZADO_S4.SP_ETL_DESCONTO`(calmonth ARRAY<STRING>)
BEGIN
	
    FOR elem in (SELECT * FROM UNNEST(calmonth) as CALMONTH)
        DO
	    
	    DELETE FROM `also-analytics-model-nonprod.3_MATERIALIZADO_S4.DESCONTO`
			WHERE CALMONTH = elem.CALMONTH;

		INSERT INTO `also-analytics-model-nonprod.3_MATERIALIZADO_S4.DESCONTO`
			SELECT
				CALMONTH,
				CAST(CALMONTH_INT AS INT64) AS CALMONTH_INT,
				CSHP_CDSHOPPING,
				INTRENO_VICNCN,
				CC_CDCONTRATO,
				BUKRS,
				XWETEXT,
				SWENR,
				SMENR,
				XMETXT,
				SSTOCKW,
				SSTCKBIS,
				RLGESCH,
				SAFE_CAST(
					CONCAT(
						SUBSTR(NTPER, 1, 4), "-", SUBSTR(NTPER, 5, 2), "-", SUBSTR(NTPER, 7, 2) 
					) AS DATE
				) AS NTPER,
				RECNNR,
				RECNTYPE,
				RECNTYPE_TEXT30,
				RECNTXT,
				PAVAL,
				SAFE_CAST(
					CONCAT(
						SUBSTR(RECNBEG, 1, 4), "-", SUBSTR(RECNBEG, 5, 2), "-", SUBSTR(RECNBEG, 7, 2) 
					) AS DATE
				) AS RECNBEG,
				SAFE_CAST(
					CONCAT(
						SUBSTR(ZZREDILJ, 1, 4), "-", SUBSTR(ZZREDILJ, 5, 2), "-", SUBSTR(ZZREDILJ, 7, 2) 
					) AS DATE
				) AS ZZREDILJ,
				SAFE_CAST(
					CONCAT(
						SUBSTR(RECNENDABS, 1, 4), "-", SUBSTR(RECNENDABS, 5, 2), "-", SUBSTR(RECNENDABS, 7, 2) 
					) AS DATE
				) AS RECNENDABS,
				CODNATPB,
				ZZCLASS_ZNATPB,
				ZCODREDE,
				ZZCLASS_ZREDE,
				ZCODABL,
				ZZCLASS_ZGRABL,
				ZCODABRASCE,
				ZZCLASS_ZGRABRASCE,
				OBJNR,
				PARTNER_TR0200,
				PARTNER_TR0600,
				PARTNER_TR0605,
				PARTNER_TR0806,
				KUNNR, 
				HKONT, 
				UMSKZ,
				SAFE_CAST(
					CONCAT(
						SUBSTR(AUGDT, 1, 4), "-", SUBSTR(AUGDT, 5, 2), "-", SUBSTR(AUGDT, 7, 2) 
					) AS DATE
				) AS AUGDT, 
				AUGBL, 
				AUGGJ, 
				ZUONR, 
				GJAHR, 
				BUZEI, 
				SHKZG, 
				VERTN, 
				REBZG, 
				REBZJ, 
				REBZZ,
				SAFE_CAST(
					CONCAT(
						SUBSTR(BUDAT, 1, 4), "-", SUBSTR(BUDAT, 5, 2), "-", SUBSTR(BUDAT, 7, 2) 
					) AS DATE
				) AS BUDAT,
				BLART,
				SAFE_CAST(
					CONCAT(
						SUBSTR(BLDAT, 1, 4), "-", SUBSTR(BLDAT, 5, 2), "-", SUBSTR(BLDAT, 7, 2) 
					) AS DATE
				) AS BLDAT, 
				GSBER, 
				CC_CDTPCONTA,
				SAFE_CAST(
					CONCAT(
						SUBSTR(ZFBDT, 1, 4), "-", SUBSTR(ZFBDT, 5, 2), "-", SUBSTR(ZFBDT, 7, 2) 
					) AS DATE
				) AS ZFBDT, 
				ZFBDT_ANO_MES, 
				BELNR, 
				BELNR_AUGBL, 
				SUM(VALOR) AS VALOR,
				SUM(WRBTR) AS WRBTR,
				CC_DIAS_VENCTO,
				MAX(CC_FQMFLART_SONAE) AS CC_FQMFLART_SONAE,
				MAX(FQMFLART) AS FQMFLART,
				SUM(VLDESC_TOT) AS VLDESC_TOT,
				SUM(VLCAR_TOT) AS VLCAR_TOT,
				SUM(VLCAR_ALUG) AS VLCAR_ALUG,
				SUM(VLCAR_REF) AS VLCAR_REF,
				SUM(VLCAR_INAG) AS VLCAR_INAG,
				SUM(VLDESC_PRE_TOT) AS VLDESC_PRE_TOT,
				SUM(VLDESC_PRE_CTO) AS VLDESC_PRE_CTO,
				SUM(VLDESC_PRE_ALUG) AS VLDESC_PRE_ALUG,
				SUM(VLDESC_PRE_LOJA_TEMP) AS VLDESC_PRE_LOJA_TEMP,
				SUM(VLDESC_PRE_MALL) AS VLDESC_PRE_MALL,
				SUM(VLDESC_PRE_MIDIA) AS VLDESC_PRE_MIDIA,
				SUM(VLDESC_PRE_ESTAC) AS VLDESC_PRE_ESTAC,
				SUM(VLDESC_PRE_LOJAS) AS VLDESC_PRE_LOJAS,
				SUM(VLDESC_PRE_COND_PAG) AS VLDESC_PRE_COND_PAG,
				SUM(VLDESC_PRE_INAG) AS VLDESC_PRE_INAG,
				SUM(VLDESC_PRE_ALUG_DOBRO) AS VLDESC_PRE_ALUG_DOBRO,
				SUM(VLDESC_PRE_EXTRA) AS VLDESC_PRE_EXTRA,
				SUM(VLDESC_POS_TOT) AS VLDESC_POS_TOT,
				SUM(VLDESC_POS_LOJA) AS VLDESC_POS_LOJA,
				SUM(VLDESC_POS_MALL) AS VLDESC_POS_MALL,
				SUM(VLDESC_POS_MIDIA) AS VLDESC_POS_MIDIA,
				SUM(VLCANCELAMENTO_TOT) AS VLCANCELAMENTO_TOT,
				SUM(VLCANCELAMENTO_LOJA) AS VLCANCELAMENTO_LOJA,
				SUM(VLCANCELAMENTO_MALL) AS VLCANCELAMENTO_MALL,
				SUM(VLCANCELAMENTO_MIDIA) AS VLCANCELAMENTO_MIDIA,
				SUM(VLDEVOLUCAO) AS VLDEVOLUCAO,
				SUM(CC_DESCONTO_PRO) AS CC_DESCONTO_PRO, 
				SUM(CC_DESCONTO_PAR) AS CC_DESCONTO_PAR,
				SUM(VLDESC_ENCARGO) AS VLDESC_ENCARGO, 
				SUM(VLDESC_FPP) AS VLDESC_FPP, 
				SUM(VLDESC_POS) AS VLDESC_POS, 
				SUM(VLDESC_PERDAO_DIVIDA) AS VLDESC_PERDAO_DIVIDA,
				SUM(VLDESC_CONDICIONAL_POS_TOT) AS VLDESC_CONDICIONAL_POS_TOT, 
				SUM(VLDESC_CONDICIONAL_PRE_TOT) AS VLDESC_CONDICIONAL_PRE_TOT,
				SUM(VLDESC_CONDICIONAL_TOT) AS VLDESC_CONDICIONAL_TOT,
				FLAG_LANC_BSEG,
				CURRENT_TIMESTAMP() AS CHANGE_TIME
			FROM `also-analytics-model-nonprod.2_NEGOCIO_S4.TF_DESCONTO_4B` (elem.CALMONTH)
			GROUP BY 
				CALMONTH, CSHP_CDSHOPPING, BUKRS, INTRENO_VICNCN, RECNNR, RECNTXT, RECNTYPE, 					RECNTYPE_TEXT30, ZZREDILJ, RECNBEG, RECNENDABS, NTPER, CC_DIAS_VENCTO, 								ZZCLASS_ZGRABL, ZCODABL, 
				CODNATPB, ZZCLASS_ZNATPB, ZCODREDE, ZZCLASS_ZREDE, ZCODABRASCE, 							      ZZCLASS_ZGRABRASCE, PARTNER_TR0200, PARTNER_TR0600, PARTNER_TR0605, 		 							PARTNER_TR0806, SWENR, XWETEXT, XMETXT, SMENR, 
				SSTOCKW, RLGESCH, SSTCKBIS, PAVAL, OBJNR, FLAG_LANC_BSEG, KUNNR, HKONT, 							BELNR, ZFBDT, ZFBDT_ANO_MES, GSBER, CC_CDTPCONTA, CALMONTH_INT, UMSKZ, AUGDT, 				AUGBL, AUGGJ, 
				ZUONR, GJAHR, BUZEI, SHKZG, VERTN, REBZG, REBZJ, REBZZ, BUDAT, BLART, BLDAT, 					CC_CDCONTRATO, BELNR_AUGBL, CHANGE_TIME;
	END FOR;	
END;