CREATE OR REPLACE PROCEDUREaliansceSonae.1_etl.financeiro.s4::SP_ETL_DESCONTO_4M (IN var_calmonth TABLE(CALMONTH STRING(6))) 
	
	 
	
	AS
BEGIN
	DECLARE VAR_I INT;
	DECLARE VAR_COUNT INT;
	DECLARE VAR_CURRENT STRING(6);
	

	SELECT COUNT(*)
	INTO VAR_COUNT
	FROM :var_calmonth;
	
	FOR VAR_I IN 0 .. :VAR_COUNT-1 DO
	    SELECT CALMONTH
	    INTO VAR_CURRENT
	    FROM :var_calmonth
	    LIMIT 1 OFFSET :VAR_I;
	    SELECT :VAR_CURRENT FROM DUMMY;
	    
	    DELETE FROM also-analytics-model-nonprod.1_AQUISICAO_S4.DESCONTO
		WHERE CALMONTH = :VAR_CURRENT;

		INSERT INTO also-analytics-model-nonprod.1_AQUISICAO_S4.DESCONTO
		(CALMONTH, CSHP_CDSHOPPING, BUKRS, INTRENO_VICNCN, RECNNR, RECNTXT, RECNTYPE, RECNTYPE_TEXT30, ZZREDILJ, RECNBEG, RECNENDABS, NTPER, CC_DIAS_VENCTO, ZZCLASS_ZGRABL, ZCODABL, 
		 CODNATPB, ZZCLASS_ZNATPB, ZCODREDE, ZZCLASS_ZREDE, ZCODABRASCE, ZZCLASS_ZGRABRASCE, PARTNER_TR0200, PARTNER_TR0600, PARTNER_TR0605, PARTNER_TR0806, SWENR, XWETEXT, XMETXT, 
		 SMENR, SSTOCKW, RLGESCH, SSTCKBIS, PAVAL, OBJNR, FLAG_LANC_BSEG, FQMFLART, CC_FQMFLART_SONAE, VLCAR_TOT, VLDESC_PRE_TOT, VLDESC_POS_TOT, VLCANCELAMENTO_TOT, VLCAR_INAG, 
		 VLCAR_ALUG, VLCAR_REF, VLDESC_PRE_MALL, VLDESC_PRE_ALUG_DOBRO, VLDESC_PRE_LOJA_TEMP, VLDESC_PRE_INAG, VLDESC_PRE_ALUG, VLDESC_PRE_COND_PAG, VLDESC_PRE_CTO, VLDESC_PRE_LOJAS, 
		 VLDESC_PRE_ESTAC, VLDESC_PRE_MIDIA, VLDESC_PRE_EXTRA, VLDESC_POS_MIDIA, VLDESC_POS_MALL, VLDESC_POS_LOJA, VLCANCELAMENTO_MIDIA, VLCANCELAMENTO_MALL, VLCANCELAMENTO_LOJA, 
		 VLDEVOLUCAO, VLDESC_TOT, KUNNR, HKONT, BELNR, WRBTR, ZFBDT, ZFBDT_ANO_MES, GSBER, CC_CDTPCONTA, CALMONTH_INT, UMSKZ, AUGDT, AUGBL, AUGGJ, ZUONR, GJAHR, BUZEI, 
		 SHKZG, VERTN, REBZG, REBZJ, REBZZ, BUDAT, BLART, BLDAT, CC_CDCONTRATO, BELNR_AUGBL, VALOR, CC_DESCONTO_PRO, CC_DESCONTO_PAR, VLDESC_ENCARGO, VLDESC_FPP, VLDESC_POS, 
		 VLDESC_PERDAO_DIVIDA, VLDESC_CONDICIONAL_TOT, VLDESC_CONDICIONAL_POS_TOT, VLDESC_CONDICIONAL_PRE_TOT, CHANGE_TIME)
			SELECT
				CALMONTH,
				CSHP_CDSHOPPING,
				BUKRS,
				INTRENO_VICNCN,
				RECNNR,
				RECNTXT,
				RECNTYPE,
				RECNTYPE_TEXT30,
				ZZREDILJ,
				RECNBEG,
				RECNENDABS,
				NTPER,
				CC_DIAS_VENCTO,
				ZZCLASS_ZGRABL,
				ZCODABL,
				CODNATPB,
				ZZCLASS_ZNATPB,
				ZCODREDE,
				ZZCLASS_ZREDE,
				ZCODABRASCE,
				ZZCLASS_ZGRABRASCE,
				PARTNER_TR0200,
				PARTNER_TR0600,
				PARTNER_TR0605,
				PARTNER_TR0806,
				SWENR,
				XWETEXT,
				XMETXT,
				SMENR,
				SSTOCKW,
				RLGESCH,
				SSTCKBIS,
				PAVAL,
				OBJNR,
				FLAG_LANC_BSEG,
				MAX(FQMFLART) AS FQMFLART,
				MAX(CC_FQMFLART_SONAE) AS CC_FQMFLART_SONAE,
				SUM(VLCAR_TOT) AS VLCAR_TOT,
				SUM(VLDESC_PRE_TOT) AS VLDESC_PRE_TOT,
				SUM(VLDESC_POS_TOT) AS VLDESC_POS_TOT,
				SUM(VLCANCELAMENTO_TOT) AS VLCANCELAMENTO_TOT,
				SUM(VLCAR_INAG) AS VLCAR_INAG,
				SUM(VLCAR_ALUG) AS VLCAR_ALUG,
				SUM(VLCAR_REF) AS VLCAR_REF,
				SUM(VLDESC_PRE_MALL) AS VLDESC_PRE_MALL,
				SUM(VLDESC_PRE_ALUG_DOBRO) AS VLDESC_PRE_ALUG_DOBRO,
				SUM(VLDESC_PRE_LOJA_TEMP) AS VLDESC_PRE_LOJA_TEMP,
				SUM(VLDESC_PRE_INAG) AS VLDESC_PRE_INAG,
				SUM(VLDESC_PRE_ALUG) AS VLDESC_PRE_ALUG,
				SUM(VLDESC_PRE_COND_PAG) AS VLDESC_PRE_COND_PAG,
				SUM(VLDESC_PRE_CTO) AS VLDESC_PRE_CTO,
				SUM(VLDESC_PRE_LOJAS) AS VLDESC_PRE_LOJAS,
				SUM(VLDESC_PRE_ESTAC) AS VLDESC_PRE_ESTAC,
				SUM(VLDESC_PRE_MIDIA) AS VLDESC_PRE_MIDIA,
				SUM(VLDESC_PRE_EXTRA) AS VLDESC_PRE_EXTRA,
				SUM(VLDESC_POS_MIDIA) AS VLDESC_POS_MIDIA,
				SUM(VLDESC_POS_MALL) AS VLDESC_POS_MALL,
				SUM(VLDESC_POS_LOJA) AS VLDESC_POS_LOJA,
				SUM(VLCANCELAMENTO_MIDIA) AS VLCANCELAMENTO_MIDIA,
				SUM(VLCANCELAMENTO_MALL) AS VLCANCELAMENTO_MALL,
				SUM(VLCANCELAMENTO_LOJA) AS VLCANCELAMENTO_LOJA,
				SUM(VLDEVOLUCAO) AS VLDEVOLUCAO,
				SUM(VLDESC_TOT) AS VLDESC_TOT,
				KUNNR, 
				HKONT, 
				BELNR, 
				SUM(WRBTR) AS WRBTR,
				ZFBDT, 
				ZFBDT_ANO_MES, 
				GSBER, 
				CC_CDTPCONTA,
				CALMONTH_INT,
				UMSKZ, 
				AUGDT, 
				AUGBL, 
				AUGGJ, 
				ZUONR, 
				GJAHR, 
				BUZEI, 
				SHKZG, 
				VERTN, 
				REBZG, 
				REBZJ, 
				REBZZ, 
				BUDAT, 
				BLART, 
				BLDAT,
				CC_CDCONTRATO,
				BELNR_AUGBL, 
				SUM(VALOR) AS VALOR,
				SUM(CC_DESCONTO_PRO) AS CC_DESCONTO_PRO, 
				SUM(CC_DESCONTO_PAR) AS CC_DESCONTO_PAR,
				SUM(VLDESC_ENCARGO) AS VLDESC_ENCARGO, 
				SUM(VLDESC_FPP) AS VLDESC_FPP, 
				SUM(VLDESC_POS) AS VLDESC_POS, 
				SUM(VLDESC_PERDAO_DIVIDA) AS VLDESC_PERDAO_DIVIDA,
				SUM(VLDESC_CONDICIONAL_TOT) AS VLDESC_CONDICIONAL_TOT,
				SUM(VLDESC_CONDICIONAL_POS_TOT) AS VLDESC_CONDICIONAL_POS_TOT, 
				SUM(VLDESC_CONDICIONAL_PRE_TOT) AS VLDESC_CONDICIONAL_PRE_TOT,
				CURRENT_TIMESTAMP() AS CHANGE_TIME
			FROM aliansceSonae.2_business.financeiro.s4::CVW_DESCONTO_4B
				(placeholder.$$IP_COMPETENCIA$$=> :VAR_CURRENT, 
				 placeholder.$$IP_ATUALIDADE_DADOS$$=>'P')
			WHERE CALMONTH = :VAR_CURRENT
			GROUP BY 
				CALMONTH, CSHP_CDSHOPPING, BUKRS, INTRENO_VICNCN, RECNNR, RECNTXT, RECNTYPE, RECNTYPE_TEXT30, ZZREDILJ, RECNBEG, RECNENDABS, NTPER, CC_DIAS_VENCTO, ZZCLASS_ZGRABL, ZCODABL, 
				CODNATPB, ZZCLASS_ZNATPB, ZCODREDE, ZZCLASS_ZREDE, ZCODABRASCE, ZZCLASS_ZGRABRASCE, PARTNER_TR0200, PARTNER_TR0600, PARTNER_TR0605, PARTNER_TR0806, SWENR, XWETEXT, XMETXT, SMENR, 
				SSTOCKW, RLGESCH, SSTCKBIS, PAVAL, OBJNR, FLAG_LANC_BSEG, KUNNR, HKONT, BELNR, ZFBDT, ZFBDT_ANO_MES, GSBER, CC_CDTPCONTA, CALMONTH_INT, UMSKZ, AUGDT, AUGBL, AUGGJ, 
				ZUONR, GJAHR, BUZEI, SHKZG, VERTN, REBZG, REBZJ, REBZZ, BUDAT, BLART, BLDAT, CC_CDCONTRATO, BELNR_AUGBL;
	END FOR;
END;