CREATE OR REPLACE PROCEDURE `also-analytics-model-nonprod.3_MATERIALIZADO_S4.DIM_CONDICAO_FAT` () 

BEGIN
		CREATE OR REPLACE TABLE `also-analytics-model-nonprod.3_MATERIALIZADO_S4.DIM_CONDICAO_FAT`
    AS
    SELECT
      CONDTYPE, CONDTYPE_TEXT30, ENC_ESPECIFICO, DESC_CARENCIA, ALUG_LIQUIDO, ENC_COMUM, ALUG_TOT, DESCONTO_PRE,
      ALUG_FATURADO, ALUG_COMPLEMENTAR, CARENCIA, ALUG_CONTRATUAL, CO_COM_ESPECIFICO, CO, TX_TRANSF, FPP, IPTU,
      NEGATIVO, DESC_TOT_RE, ALUG_MIN_MESES_ANT, CURRENT_DATETIME('America/Sao_Paulo') AS CHANGE_TIME
		FROM `also-analytics-model-nonprod.2_NEGOCIO_S4.TF_CONDICAO_FAT_4B`();
END;
