CREATE OR REPLACE PROCEDURE `also-analytics-model-nonprod.3_MATERIALIZADO_S4.SP_ETL_VENDA_AUDITADA` (calmonth ARRAY<STRING>) 

BEGIN

    FOR elem in (SELECT * FROM UNNEST(calmonth) as CALMONTH)
        DO 

	    DELETE FROM `also-analytics-model-nonprod.3_MATERIALIZADO_S4.VENDA_AUDITADA`
		WHERE DATE_TRUNC(RPDATE, MONTH) = PARSE_DATE('%Y%m%d', elem.CALMONTH || '01');

		INSERT INTO `also-analytics-model-nonprod.3_MATERIALIZADO_S4.VENDA_AUDITADA`
		( CSHP_CDSHOPPING, INTRENO_VICNCN, CSHP_CDCONTRATO, CC_CDCONTRATO, CSHP_CDCONTRATO_MXM, INTRENO_ECC, INTRENO, BUKRS, 
		  RECNNR, CALMONTH, RPDATE, SALESTYPE, SALESTYPE_TEXT, ZZNMFAN, RECNTXT, SMENR, XMETXT, CDTPAQUISICAO, 
		  ZZGRPAT_BR, ZZSUGRP_BR, ZZATIVM_BR, SNUNR, CC_CDGRUPOABL, CDTIPOUNL, KEY_GRPABRASCE, KEY_ATVABRASCE, FQMFLART, 
		  CC_FQMFLART_SONAE, GROSS_SALES_AUD_FIS, GROSS_SALES_REDU_Z, GROSS_SALES_PROJET, VOLVED_AUD, CHANGE_TIME)
			SELECT
				CSHP_CDSHOPPING,
				INTRENO_VICNCN,
				CSHP_CDCONTRATO,
				CC_CDCONTRATO,
				CSHP_CDCONTRATO_MXM,
				INTRENO_ECC,
				INTRENO,
				BUKRS,
				RECNNR,
				CALMONTH,
				RPDATE,
				SALESTYPE,
				SALESTYPE_TEXT,
				ZZNMFAN,
				RECNTXT,
				SMENR,
				XMETXT,
				CDTPAQUISICAO,
				ZZGRPAT_BR,
				ZZSUGRP_BR,
				ZZATIVM_BR,
				SNUNR,
				CC_CDGRUPOABL,
				CDTIPOUNL,
				KEY_GRPABRASCE,
				KEY_ATVABRASCE,
				FQMFLART,
				CC_FQMFLART_SONAE,
				GROSS_SALES_AUD_FIS,
				GROSS_SALES_REDU_Z,
				GROSS_SALES_PROJET,
				VOLVED_AUD,
				CURRENT_DATETIME('America/Sao_Paulo') AS CHANGE_TIME
			FROM `also-analytics-model-nonprod.2_NEGOCIO_S4.TF_VENDA_AUDITADA_4B`()
			WHERE CALMONTH = elem.CALMONTH;
	END FOR;
	
END;
