CREATE OR REPLACE PROCEDURE `also-analytics-model-nonprod.3_MATERIALIZADO_S4.SP_ETL_VENDA_INTRAMALL` (calmonth ARRAY<STRING>) 
	
BEGIN
		
	FOR elem in (SELECT * FROM UNNEST(calmonth) as CALMONTH)
        DO	
	    
	    DELETE FROM `also-analytics-model-nonprod.3_MATERIALIZADO_S4.VENDA_INTRAMALL`
		WHERE DATE_TRUNC(RPDATE, MONTH) = PARSE_DATE('%Y%m%d', elem.CALMONTH || '01');

		INSERT INTO `also-analytics-model-nonprod.3_MATERIALIZADO_S4.VENDA_INTRAMALL`
		( INTRENO_VICNCN, CSHP_CDSHOPPING, BUKRS, CDCONTRATO, CDCONTRATOS, CC_CDCONTRATO, RECNNR, SWENR, XMETXT, 
		  CDUNIDADE, NMFANTASIA, CSHP_CDTIPOUNL, CDTPAQUISICAO, RECNTXT, PROTOCOLO, DTINAUGURA, DTENCERRAMENTO, 
		  FLGWEEKINF, SOURCE_SYSTEM, YEAR, MONTH, MONTH_YEAR, CALMONTH, WEEK, WEEK_MONTH, WEEK_NUM, DTSTARTWEEK, 
		  DTFINISHWEEK, DATE_SQL, RPDATE, SALESREPORTTYPE, SALESREPORTTYPE_TEXT, SALESTYPE, FLGINFORMOU, SMENR, 
		  INTRENO_ECC, ZZNMFAN, CSHP_CDCONTRATO_MXM, CSHP_CDCONTRATO, CC_CDGRUPOABL, SNUNR, INTRENO, ZZATIVM_BR, 
		  ZZSUGRP_BR, KEY_ATVABRASCE, ZZGRPAT_BR, KEY_GRPABRASCE, CDTIPOUNL, COUNTER_FLGINFORMOU, COUNTER_WEEK_SUM, 
		  VBDIAUTIL, NUPRAZOINFVND, COUNTER_SUM, COUNTER, NET_SALES, VLVENDA, GROSS_SALES, SHOP_WEEK_SUM, CC_VOLVED, 
		  FQMFLART, CC_FQMFLART_SONAE, CHANGE_TIME)
			SELECT
				INTRENO_VICNCN,
				CSHP_CDSHOPPING,
				BUKRS,
				CDCONTRATO,
				CDCONTRATOS,
				CC_CDCONTRATO,
				RECNNR,
				SWENR,
				XMETXT,
				CDUNIDADE,
				NMFANTASIA,
				CSHP_CDTIPOUNL,
				CDTPAQUISICAO,
				RECNTXT,
				PROTOCOLO,
				DTINAUGURA,
				DTENCERRAMENTO,
				FLGWEEKINF,
				SOURCE_SYSTEM,
				YEAR,
				MONTH,
				MONTH_YEAR,
				CALMONTH,
				WEEK,
				WEEK_MONTH,
				WEEK_NUM,
				DTSTARTWEEK,
				DTFINISHWEEK,
				DATE_SQL,
				RPDATE,
				SALESREPORTTYPE,
				SALESREPORTTYPE_TEXT,
				SALESTYPE,
				FLGINFORMOU,
				SMENR,
				INTRENO_ECC,
				ZZNMFAN,
				CSHP_CDCONTRATO_MXM,
				CSHP_CDCONTRATO,
				CC_CDGRUPOABL,
				SNUNR,
				INTRENO,
				ZZATIVM_BR,
				ZZSUGRP_BR,
				KEY_ATVABRASCE,
				ZZGRPAT_BR,
				KEY_GRPABRASCE,
				CDTIPOUNL,
				SUM(COUNTER_FLGINFORMOU) AS COUNTER_FLGINFORMOU,
				SUM(COUNTER_WEEK_SUM) AS COUNTER_WEEK_SUM,
				SUM(VBDIAUTIL) AS VBDIAUTIL,
				SUM(NUPRAZOINFVND) AS NUPRAZOINFVND,
				SUM(COUNTER_SUM) AS COUNTER_SUM,
				SUM(COUNTER) AS COUNTER,
				SUM(NET_SALES) AS NET_SALES,
				SUM(VLVENDA) AS VLVENDA,
				SUM(GROSS_SALES) AS GROSS_SALES,
				SUM(SHOP_WEEK_SUM) AS SHOP_WEEK_SUM,
				SUM(CC_VOLVED) AS CC_VOLVED,
				SUM(FQMFLART) AS FQMFLART,
				SUM(CC_FQMFLART_SONAE) AS CC_FQMFLART_SONAE,
				CURRENT_DATETIME('America/Sao_Paulo') AS CHANGE_TIME
			FROM `also-analytics-model-nonprod.2_NEGOCIO_S4.TF_VENDA_INTRAMALL_4B`()
			WHERE CALMONTH = elem.CALMONTH
			GROUP BY 
				INTRENO_VICNCN, CSHP_CDSHOPPING, BUKRS, CDCONTRATO, CDCONTRATOS, CC_CDCONTRATO, RECNNR, SWENR, 
				XMETXT, CDUNIDADE, NMFANTASIA, CSHP_CDTIPOUNL, CDTPAQUISICAO, RECNTXT, PROTOCOLO, DTINAUGURA, 
				DTENCERRAMENTO, FLGWEEKINF, SOURCE_SYSTEM, YEAR, MONTH, MONTH_YEAR, CALMONTH, WEEK, WEEK_MONTH, 
				WEEK_NUM, DTSTARTWEEK, DTFINISHWEEK, DATE_SQL, RPDATE, SALESREPORTTYPE, SALESREPORTTYPE_TEXT, 
				SALESTYPE, FLGINFORMOU, SMENR, INTRENO_ECC, ZZNMFAN, CSHP_CDCONTRATO_MXM, CSHP_CDCONTRATO, 
				CC_CDGRUPOABL, SNUNR, INTRENO, ZZATIVM_BR, ZZSUGRP_BR, KEY_ATVABRASCE, ZZGRPAT_BR, KEY_GRPABRASCE, 
				CDTIPOUNL;
	END FOR;
END;
