CREATE OR REPLACE PROCEDURE `also-analytics-model-nonprod.3_MATERIALIZADO_S4.FLUXO_FINANCEIRO_RE` (calmonth ARRAY<STRING>)
BEGIN

DECLARE min_calmonth STRING;
SET min_calmonth = (SELECT min(value) FROM UNNEST(calmonth) as value);

FOR elem in (SELECT CALMONTH
              FROM `also-analytics-model-nonprod.1_AQUISICAO_MXM.dim_tempo_mensal`
              WHERE 
              CALMONTH <> 000000 AND
              PARSE_DATE('%Y%m', CALMONTH) 
              BETWEEN 
              PARSE_DATE('%Y%m', min_calmonth)--calmonth[ORDINAL(1)]) 
              AND 
              DATE_ADD(PARSE_DATE('%Y%m', min_calmonth), INTERVAL 1 YEAR))
    DO
    DELETE 
        FROM `also-analytics-model-nonprod.3_MATERIALIZADO_S4.FLUXO_FINANCEIRO_RE`
      WHERE CALMONTH = elem.CALMONTH;

      INSERT INTO `also-analytics-model-nonprod.3_MATERIALIZADO_S4.FLUXO_FINANCEIRO_RE`
      (CALMONTH, CSHP_CDSHOPPING, INTRENO_VICNCN, CC_CDCONTRATO, RECNNR, ATTRHY, AMMRHY, BUKRS, CFPAYGUID, CONDGUID, REFGUID, DBERVON, 
      DBERBIS, DFAELL, DDISPO, ATAGE, FLOWTYPE, XFLOWTYPE, ORIGFLOWTYPE, REFFLOWREL, CFSTATUS, CFSTATUS_TEXT, FDELETE, PARTNEROBJNR, 
      CONDTYPE, CONDTYPE_TEXT20, POSTINGDATE, DOCUMENTDATE, BOOK_FLOWTYPE, BOOK_REFFLOWREL, REVERSAL_FOR, FOLLOWUP_FOR, BNWHR, BBWHR, 
      ALUG_CONTRATUAL, ALUG_FATURADO, ALUG_LIQUIDO, ALUG_TOT, DESC_CARENCIA, ALUG_COMPLEMENTAR, ENC_COMUM, ENC_ESPECIFICO, FPP, CO, 
      CO_COM_ESPECIFICO, CARENCIA, DESCONTO_PRE, SSOLHAB, IPTU, TX_TRANSF, FLAG_CTO, ICON_CFSTATUS, ICON_CFSTATUS_TEXT, RENTPERCENT, 
      SALES, SALESRENT, PAYNET, RECEIVABLENET, BALANCENET, CHANGE_TIME)
        SELECT
          CALMONTH,
          CSHP_CDSHOPPING,
          INTRENO_VICNCN,
          CC_CDCONTRATO,
          RECNNR,
          ATTRHY,
          AMMRHY,
          BUKRS,
          CFPAYGUID,
          CONDGUID,
          REFGUID,
          DBERVON,
          DBERBIS,
          DFAELL,
          DDISPO,
          ATAGE,
          FLOWTYPE,
          XFLOWTYPE,
          ORIGFLOWTYPE,
          REFFLOWREL,
          CFSTATUS,
          CFSTATUS_TEXT,
          FDELETE,
          PARTNEROBJNR,
          CONDTYPE,
          CONDTYPE_TEXT20,
          POSTINGDATE,
          DOCUMENTDATE,
          BOOK_FLOWTYPE,
          BOOK_REFFLOWREL,
          REVERSAL_FOR,
          FOLLOWUP_FOR,
          SUM(BNWHR) AS BNWHR,
          SUM(BBWHR) AS BBWHR,
          SUM(ALUG_CONTRATUAL) AS ALUG_CONTRATUAL,
          SUM(ALUG_FATURADO) AS ALUG_FATURADO,
          SUM(ALUG_LIQUIDO) AS ALUG_LIQUIDO,
          SUM(ALUG_TOT) AS ALUG_TOT,
          SUM(DESC_CARENCIA) AS DESC_CARENCIA,
          SUM(ALUG_COMPLEMENTAR) AS ALUG_COMPLEMENTAR,
          SUM(ENC_COMUM) AS ENC_COMUM,
          SUM(ENC_ESPECIFICO) AS ENC_ESPECIFICO,
          SUM(FPP) AS FPP,
          SUM(CO) AS CO,
          SUM(CO_COM_ESPECIFICO) AS CO_COM_ESPECIFICO,
          SUM(CARENCIA) AS CARENCIA,
          SUM(DESCONTO_PRE) AS DESCONTO_PRE, 
          SSOLHAB,
          SUM(IPTU) AS IPTU, 
          SUM(TX_TRANSF) AS TX_TRANSF,
          FLAG_CTO,
          ICON_CFSTATUS, 
          ICON_CFSTATUS_TEXT,
          SUM(RENTPERCENT) AS RENTPERCENT, 
          SUM(SALES) AS SALES, 
          SUM(SALESRENT) AS SALESRENT,
          SUM(PAYNET) AS PAYNET, 
          SUM(RECEIVABLENET) AS RECEIVABLENET, 
          SUM(BALANCENET) AS BALANCENET,
          CURRENT_TIMESTAMP() AS CHANGE_TIME
        FROM `also-analytics-model-nonprod.2_NEGOCIO_S4.TF_FLUXO_FINANCEIRO_RE_4B`()
        WHERE CALMONTH = elem.CALMONTH
        GROUP BY 
        CALMONTH, CSHP_CDSHOPPING, INTRENO_VICNCN, CC_CDCONTRATO, RECNNR, ATTRHY, AMMRHY, BUKRS, CFPAYGUID, CONDGUID, REFGUID, DBERVON, 
        DBERBIS, DFAELL, DDISPO, ATAGE, FLOWTYPE, XFLOWTYPE, ORIGFLOWTYPE, REFFLOWREL, CFSTATUS, CFSTATUS_TEXT, FDELETE, PARTNEROBJNR, 
        CONDTYPE, CONDTYPE_TEXT20, POSTINGDATE, DOCUMENTDATE, BOOK_FLOWTYPE, BOOK_REFFLOWREL, REVERSAL_FOR, FOLLOWUP_FOR, SSOLHAB, FLAG_CTO,
        ICON_CFSTATUS, ICON_CFSTATUS_TEXT;
      END FOR;
END;