CREATE OR REPLACE PROCEDURE `also-analytics-model-nonprod.3_MATERIALIZADO_S4.SP_ETL_VENDA_DIARIA` (calmonth ARRAY<STRING>)
BEGIN
		
	FOR elem in (SELECT * FROM UNNEST(calmonth) as CALMONTH)
        DO
	    
	    DELETE FROM `also-analytics-model-nonprod.3_MATERIALIZADO_S4.VENDA_DIARIA`
			WHERE DATE_TRUNC(RPDATE, MONTH) = PARSE_DATE('%Y%m%d', elem.CALMONTH || '01');

		INSERT INTO `also-analytics-model-nonprod.3_MATERIALIZADO_S4.VENDA_DIARIA`
			SELECT
				CSHP_CDSHOPPING,
				BUKRS,
				INTRENO_VICNCN,
				CSHP_CDCONTRATO,
				INTRENO,
				INTRENO_ECC,
				CSHP_CDCONTRATO_MXM,
				CC_CDCONTRATO,
				CALMONTH,
				RPDATE,
				SALESTYPE,
				FQMFLART,
				CDTPAQUISICAO,
				SMENR,
				XMETXT,
				ZZGRPAT_BR,
				ZZSUGRP_BR,
				ZZATIVM_BR,
				SNUNR,
				CC_CDGRUPOABL,
				CDTIPOUNL,
				KEY_GRPABRASCE,
				KEY_ATVABRASCE,
				ZZNMFAN,
				RECNTXT,
				SUM(GREATEST_CC_VOLVED) AS CC_VOLVED,
				CC_FQMFLART_SONAE,
				SUM(CC_VOLVED_COM_FQMFLART) AS CC_VOLVED_COM_FQMFLART,
				CC_FQMFLART_COM_VOLVED,
				-- AUDITADA METRICS
				SUM(SUM_GROSS_SALES_AUD_FIS) AS GROSS_SALES_AUD_FIS,
				SUM(SUM_GROSS_SALES_REDU_Z) AS GROSS_SALES_REDU_Z,
				SUM(SUM_GROSS_SALES_PROJET) AS GROSS_SALES_PROJET,
				-- INTRAMALL METRICS
				SUM(SUM_NET_SALES_INTRAMALL) AS NET_SALES_INTRAMALL, 
				SUM(SUM_GROSS_SALES_INTRAMALL) AS GROSS_SALES_INTRAMALL,
				-- GENERAL METRICS
				SUM(GREATEST_NET_SALES) AS NET_SALES,
				SUM(GREATEST_GROSS_SALES) AS GROSS_SALES,
				CURRENT_DATETIME('America/Sao_Paulo') AS CHANGE_TIME
			FROM `also-analytics-model-nonprod.2_NEGOCIO_S4.TF_VENDA_DIARIA_4B`()
			WHERE CALMONTH = elem.CALMONTH
			GROUP BY 
				CSHP_CDSHOPPING,
				BUKRS,
				INTRENO_VICNCN,
				CSHP_CDCONTRATO,
				INTRENO,
				INTRENO_ECC,
				CSHP_CDCONTRATO_MXM,
				CC_CDCONTRATO,
				CALMONTH,
				RPDATE,
				SALESTYPE,
				FQMFLART,
				CDTPAQUISICAO,
				SMENR,
				XMETXT,
				ZZGRPAT_BR,
				ZZSUGRP_BR,
				ZZATIVM_BR,
				SNUNR,
				CC_CDGRUPOABL,
				CDTIPOUNL,
				KEY_GRPABRASCE,
				KEY_ATVABRASCE,
				ZZNMFAN,
				RECNTXT,
				CC_FQMFLART_SONAE,
				CC_FQMFLART_COM_VOLVED;
	END FOR;
END;
